Prevent users from adding IPs as domains

diff --git a/bin/v-add-dns-domain b/bin/v-add-dns-domain
--- a/bin/v-add-dns-domain
+++ b/bin/v-add-dns-domain
@@ -61,6 +61,10 @@ if [ "$($BIN/v-list-dns-domain $user $domain_idn plain |cut -f 1) " != "$domain"
 else
     is_domain_new 'dns' "$domain"
 fi
+if [ -z "$(is_ip_format_valid $domain)" ]; then
+    echo "Error: Invalid domain format. IP address detected as input." 
+    exit 1
+fi
 
 is_package_full 'DNS_DOMAINS'
 template=$(get_user_value '$DNS_TEMPLATE')
diff --git a/bin/v-add-mail-domain b/bin/v-add-mail-domain
--- a/bin/v-add-mail-domain
+++ b/bin/v-add-mail-domain
@@ -60,6 +60,10 @@ if [ "$($BIN/v-list-mail-domain $user $domain_idn plain |cut -f 1) " != "$domain
 else
     is_domain_new 'mail' "$domain"
 fi
+if [ -z "$(is_ip_format_valid $domain)" ]; then
+    echo "Error: Invalid domain format. IP address detected as input." 
+    exit 1
+fi
 
 is_package_full 'MAIL_DOMAINS'
 is_dir_symlink $HOMEDIR/$user/mail
diff --git a/bin/v-add-web-domain b/bin/v-add-web-domain
--- a/bin/v-add-web-domain
+++ b/bin/v-add-web-domain
@@ -62,6 +62,10 @@ if [ "$($BIN/v-list-web-domain $user $domain_idn plain |cut -f 1) " != "$domain"
 else
     is_domain_new 'web' "$domain,$aliases"
 fi
+if [ -z "$(is_ip_format_valid $domain)" ]; then
+    echo "Error: Invalid domain format. IP address detected as input." 
+    exit 1
+fi
 
 is_dir_symlink "$HOMEDIR/$user/web"
 is_dir_symlink "$HOMEDIR/$user/web/$domain"
