Minot spelling changes.

diff --git a/bin/v-add-web-domain-ssl-force b/bin/v-add-web-domain-ssl-force
--- a/bin/v-add-web-domain-ssl-force
+++ b/bin/v-add-web-domain-ssl-force
@@ -38,7 +38,7 @@ eval $(grep "DOMAIN='$domain'" $USER_DATA/web.conf)
 
 # Check if SSL is enabled
 if [ "$SSL" != 'yes' ]; then
-    echo "Error: ssl is not enabled"
+    echo "Error: SSL is not enabled"
     exit $E_NOTEXIST
 fi
 
@@ -76,10 +76,10 @@ fi
 
 # Restart web server
 $BIN/v-restart-web
-check_result $? "Web restart failed" >/dev/null
+check_result $? "Web restart failed" > /dev/null
 
 # Restart proxy
 $BIN/v-restart-proxy
-check_result $? "Proxy restart failed" >/dev/null
+check_result $? "Proxy restart failed" > /dev/null
 
 exit
