Return error on user createtion failure
When aditional password enforcements are in place Hestia didn't output an error message

diff --git a/bin/v-add-user b/bin/v-add-user
--- a/bin/v-add-user
+++ b/bin/v-add-user
@@ -62,6 +62,13 @@ check_result $? "user creation failed" $E_INVALID
 # Adding password
 echo "$user:$password" | /usr/sbin/chpasswd
 
+if [ $? -ne 0 ]; then 
+    # Delete user on failure again
+    /usr/sbin/deluser "$user"
+    echo "Error: Password not accepted by PAM requirements"
+    exit 2
+fi
+
 # Add a general group for normal users created by Hestia
 if [ -z "$(grep ^hestia-users: /etc/group)" ]; then
     groupadd --system "hestia-users"
diff --git a/bin/v-add-web-domain-ftp b/bin/v-add-web-domain-ftp
--- a/bin/v-add-web-domain-ftp
+++ b/bin/v-add-web-domain-ftp
@@ -93,6 +93,14 @@ fi
 
 # Set ftp user password
 echo "$ftp_user:$password" | /usr/sbin/chpasswd
+
+if [ $? -ne 0 ]; then 
+    # Delete user on failure again
+    /usr/sbin/deluser "$ftp_user"
+    echo "Error: Password not accepted by PAM"
+    exit 2
+fi
+
 ftp_md5=$(awk -v user=$ftp_user -F : 'user == $1 {print $2}' /etc/shadow)
 
 # Adding jailed sftp env
diff --git a/bin/v-change-user-password b/bin/v-change-user-password
--- a/bin/v-change-user-password
+++ b/bin/v-change-user-password
@@ -47,6 +47,12 @@ check_hestia_demo_mode
 
 # Changing user password
 echo "$user:$password" | /usr/sbin/chpasswd
+
+if [ $? -ne 0 ]; then 
+    echo "Error: Password not changed due to PAM requirements"
+    exit 2
+fi
+
 md5=$(awk -v user=$user -F : 'user == $1 {print $2}' /etc/shadow)
 
 if [ "$user" = 'admin' ] && [ -e "$HESTIA/web/reset.admin" ]; then
diff --git a/bin/v-change-web-domain-ftp-password b/bin/v-change-web-domain-ftp-password
--- a/bin/v-change-web-domain-ftp-password
+++ b/bin/v-change-web-domain-ftp-password
@@ -56,6 +56,12 @@ check_hestia_demo_mode
 
 # Changing ftp user password
 echo "$ftp_user:$password" | /usr/sbin/chpasswd
+
+if [ $? -ne 0 ]; then 
+    echo "Error: Password not changed due to PAM requirements"
+    exit 2
+fi
+
 ftp_md5=$(awk -v user=$ftp_user -F : 'user == $1 {print $2}' /etc/shadow)
 
 
