Enforce min duration

diff --git a/bin/v-add-fastcgi-cache b/bin/v-add-fastcgi-cache
--- a/bin/v-add-fastcgi-cache
+++ b/bin/v-add-fastcgi-cache
@@ -42,6 +42,12 @@ if ! [[ "$duration" =~ ^[0-9].*[s|m|d]$ ]]; then
    echo "Invalid duration";
    exit 2;
 fi
+
+if [[ "$duration" =~ ^[0].*[s|m|d]$ ]]; then
+   echo "Invalid duration";
+   exit 2;
+fi
+
 # Perform verification if read-only mode is enabled
 check_hestia_demo_mode
 
