Update v-add-fastcgi-cache

diff --git a/bin/v-add-fastcgi-cache b/bin/v-add-fastcgi-cache
--- a/bin/v-add-fastcgi-cache
+++ b/bin/v-add-fastcgi-cache
@@ -1,12 +1,12 @@
 #!/bin/bash
 # info: Add FastCGI nginx support
-# options: USER DOMAIN [LENTGH] [DEBUG] [RESTART]
+# options: USER DOMAIN [DURATION] [DEBUG] [RESTART]
 # labels: hestia web
 #
 # example: v-add-fastcgi-cache user domain.tld 30m
 #
 # The function enables FastCGI cache for nginx
-# For Length only use time in seconds (10s) minutes (10m) or days (10d)
+# Acceptable values for duration is time in seconds (10s) minutes (10m) or days (10d)
 # Add "yes" as last parameter to append debug information to response headers
 
 #----------------------------------------------------------#
@@ -16,7 +16,7 @@
 # Argument definition
 user=$1
 domain=$2
-length=${3-30m}
+duration=${3-30m}
 debug=${4-no}
 restart=${5-no}
 
@@ -36,8 +36,8 @@ is_object_unsuspended 'user' 'USER' "$user"
 is_object_valid 'web' 'DOMAIN' "$domain"
 is_object_unsuspended 'web' 'DOMAIN' "$domain"
 
-if ! [[ "$length" =~ ^[0-9].*[s|m|d]$ ]]; then
-   echo "Invalid length";
+if ! [[ "$duration" =~ ^[0-9].*[s|m|d]$ ]]; then
+   echo "Invalid duration";
    exit 2;
 fi
 # Perform verification if read-only mode is enabled
@@ -51,7 +51,7 @@ check_hestia_demo_mode
 # Load domain data
 parse_object_kv_list $(grep "DOMAIN='$domain'" $USER_DATA/web.conf)
 
-# Check if nginx is not in proxy mode
+# Check that nginx is not in proxy mode
 if [ "$WEB_SYSTEM" != 'nginx' ]; then
     echo "Error: nginx is in proxy mode"
     exit $E_NOTEXIST
@@ -103,13 +103,13 @@ mkdir -p /var/cache/nginx/micro/$domain
 if [ -z "$FASTCGI_CACHE" ]; then
     add_object_key "web" 'DOMAIN' "$domain" 'FASTCGI_CACHE' 'ALIAS'
 fi
-if [ -z "$FASTCGI_LENGTH" ]; then
-    add_object_key "web" 'DOMAIN' "$domain" 'FASTCGI_LENGTH' 'ALIAS'
+if [ -z "$FASTCGI_DURATION" ]; then
+    add_object_key "web" 'DOMAIN' "$domain" 'FASTCGI_DURATION' 'ALIAS'
 fi
 
 # Set FastCGI cache flag to enabled
 update_object_value 'web' 'DOMAIN' "$domain" '$FASTCGI_CACHE' 'yes'
-update_object_value 'web' 'DOMAIN' "$domain" 'FASTCGI_LENGTH' "$length"
+update_object_value 'web' 'DOMAIN' "$domain" 'FASTCGI_DURATION' "$duration"
 
 if [ "$restart" = "yes" ]; then
     # Restart web server
