Re-format shell files, nginx files and .sql files

diff --git a/bin/v-add-fs-archive b/bin/v-add-fs-archive
--- a/bin/v-add-fs-archive
+++ b/bin/v-add-fs-archive
@@ -31,55 +31,55 @@ is_object_valid 'user' 'USER' "$user"
 check_hestia_demo_mode
 
 # Checking user homedir
-homedir=$(grep "^$user:" /etc/passwd |cut -f 6 -d :)
+homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z "$homedir" ]; then
-    echo "Error: user home directory doesn't exist"
-    exit 12
+	echo "Error: user home directory doesn't exist"
+	exit 12
 fi
 
 # Checking archive
 if [ -e "$archive" ]; then
-    echo "Error: archive already exist $archive"
-    exit 1
+	echo "Error: archive already exist $archive"
+	exit 1
 fi
 
 # Checking source path
 IFS=$'\n'
 i=1
 for src in $*; do
-    if [ "$i" -gt 2 ]; then
-        rpath=$(readlink -f "$src")
-        if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-            echo "Error: invalid source path $src"
-            exit 1
-        fi
-    fi
-    ((i++))
+	if [ "$i" -gt 2 ]; then
+		rpath=$(readlink -f "$src")
+		if [ -z "$(echo $rpath | egrep "^/tmp|^$homedir")" ]; then
+			echo "Error: invalid source path $src"
+			exit 1
+		fi
+	fi
+	((i++))
 done
 
 i=1
 for src in $*; do
-    if [ "$i" -gt 2 ]; then
-        # Deleting leading home path
-        src=$(echo "$src"| sed -e "s|/home/$user/||")
+	if [ "$i" -gt 2 ]; then
+		# Deleting leading home path
+		src=$(echo "$src" | sed -e "s|/home/$user/||")
 
-        # Creating tar.gz archive
-        user_exec tar -rf "${archive/.gz/}" -C /home/$user $src >/dev/null 2>&1
-        if [ "$?" -ne 0 ]; then
-            echo "Error: archive $archive was not created"
-            exit 3
-        fi
-    fi
-    ((i++))
+		# Creating tar.gz archive
+		user_exec tar -rf "${archive/.gz/}" -C /home/$user $src > /dev/null 2>&1
+		if [ "$?" -ne 0 ]; then
+			echo "Error: archive $archive was not created"
+			exit 3
+		fi
+	fi
+	((i++))
 done
 
 # Checking gzip
 if [[ "$archive" =~ \.gz$ ]]; then
-    user_exec gzip "${archive/.gz/}" >/dev/null 2>&1
-    if [ "$?" -ne 0 ]; then
-        echo "Error: archive $archive was not gziped"
-        exit 3
-    fi
+	user_exec gzip "${archive/.gz/}" > /dev/null 2>&1
+	if [ "$?" -ne 0 ]; then
+		echo "Error: archive $archive was not gziped"
+		exit 3
+	fi
 fi
 
 exit
diff --git a/bin/v-add-mail-account-forward b/bin/v-add-mail-account-forward
--- a/bin/v-add-mail-account-forward
+++ b/bin/v-add-mail-account-forward
@@ -37,8 +37,8 @@ format_domain_idn
 
 check_args '4' "$#" 'USER DOMAIN ACCOUNT FORWARD'
 is_format_valid 'user' 'domain' 'account'
-if [ "$email_forward"  != ':blackhole:' ]; then
-    is_format_valid 'email_forward'
+if [ "$email_forward" != ':blackhole:' ]; then
+	is_format_valid 'email_forward'
 fi
 is_system_enabled "$MAIL_SYSTEM" 'MAIL_SYSTEM'
 is_object_valid 'user' 'USER' "$user"
@@ -49,9 +49,9 @@ is_object_valid "mail/$domain" 'ACCOUNT' "$account"
 is_object_unsuspended "mail/$domain" 'ACCOUNT' "$account"
 fwd=$(get_object_value "mail/$domain" 'ACCOUNT' "$account" '$FWD')
 if [ -n "$(echo $fwd | grep -w "$email_forward")" ]; then
-    echo "Error: forward $email_forward exists"
-    log_event "$E_EXISTS" "$ARGUMENTS"
-    exit $E_EXISTS
+	echo "Error: forward $email_forward exists"
+	log_event "$E_EXISTS" "$ARGUMENTS"
+	exit $E_EXISTS
 fi
 
 # Perform verification if read-only mode is enabled
@@ -63,15 +63,15 @@ check_hestia_demo_mode
 
 # Define fwd string
 if [ -z "$fwd" ]; then
-    fwd="$email_forward"
+	fwd="$email_forward"
 else
-    fwd="$fwd,$email_forward"
+	fwd="$fwd,$email_forward"
 fi
 
 # Adding forward to exim
 if [[ "$MAIL_SYSTEM" =~ exim ]]; then
-    sed -i "/^$account@$domain_idn:/ d" $HOMEDIR/$user/conf/mail/$domain/aliases
-    echo "$account@$domain_idn:$fwd" >> $HOMEDIR/$user/conf/mail/$domain/aliases
+	sed -i "/^$account@$domain_idn:/ d" $HOMEDIR/$user/conf/mail/$domain/aliases
+	echo "$account@$domain_idn:$fwd" >> $HOMEDIR/$user/conf/mail/$domain/aliases
 fi
 
 #----------------------------------------------------------#
@@ -79,7 +79,7 @@ fi
 #----------------------------------------------------------#
 
 # Updating config
-update_object_value "mail/$domain" 'ACCOUNT' "$account"  '$FWD' "$fwd"
+update_object_value "mail/$domain" 'ACCOUNT' "$account" '$FWD' "$fwd"
 
 # Logging
 $BIN/v-log-action "$user" "Warning" "Mail" "Mail forwarding on mail account $account@$domain enabled (send to: $email_forward)."
diff --git a/bin/v-add-mail-account-fwd-only b/bin/v-add-mail-account-fwd-only
--- a/bin/v-add-mail-account-fwd-only
+++ b/bin/v-add-mail-account-fwd-only
@@ -28,9 +28,9 @@ source_conf "$HESTIA/conf/hestia.conf"
 
 # Define mail user
 if [ "$MAIL_SYSTEM" = 'exim4' ]; then
-    MAIL_USER=Debian-exim
+	MAIL_USER=Debian-exim
 else
-    MAIL_USER=exim
+	MAIL_USER=exim
 fi
 
 # Additional argument formatting
@@ -53,9 +53,9 @@ is_object_valid "mail/$domain" 'ACCOUNT' "$account"
 is_object_unsuspended "mail/$domain" 'ACCOUNT' "$account"
 fwd=$(get_object_value "mail/$domain" 'ACCOUNT' "$account" '$FWD')
 if [ -z "$fwd" ]; then
-    echo "Error: forward doesn't exist"
-    log_event "$E_NOTEXIST" "$ARGUMENTS"
-    exit "$E_NOTEXIST"
+	echo "Error: forward doesn't exist"
+	log_event "$E_NOTEXIST" "$ARGUMENTS"
+	exit "$E_NOTEXIST"
 fi
 
 # Perform verification if read-only mode is enabled
@@ -67,10 +67,9 @@ check_hestia_demo_mode
 
 # Adding account to fwd_only
 if [[ "$MAIL_SYSTEM" =~ exim ]]; then
-    echo "$account" >> $HOMEDIR/$user/conf/mail/$domain/fwd_only
-    chown -R $MAIL_USER:mail $HOMEDIR/$user/conf/mail/$domain/fwd_only
+	echo "$account" >> $HOMEDIR/$user/conf/mail/$domain/fwd_only
+	chown -R $MAIL_USER:mail $HOMEDIR/$user/conf/mail/$domain/fwd_only
 fi
-
 
 #----------------------------------------------------------#
 #                       Hestia                             #
@@ -78,7 +77,7 @@ fi
 
 # Updating config
 add_object_key "mail/$domain" 'ACCOUNT' "$account" 'FWD_ONLY' 'MD5'
-update_object_value "mail/$domain" 'ACCOUNT' "$account"  '$FWD_ONLY' "yes"
+update_object_value "mail/$domain" 'ACCOUNT' "$account" '$FWD_ONLY' "yes"
 
 # Logging
 $BIN/v-log-action "$user" "Warning" "Mail" "Forward-only flag enabled on mail account $account@$domain."
diff --git a/bin/v-add-mail-domain b/bin/v-add-mail-domain
--- a/bin/v-add-mail-domain
+++ b/bin/v-add-mail-domain
@@ -36,9 +36,9 @@ source_conf "$HESTIA/conf/hestia.conf"
 
 # Define mail user
 if [ "$MAIL_SYSTEM" = 'exim4' ]; then
-    MAIL_USER=Debian-exim
+	MAIL_USER=Debian-exim
 else
-    MAIL_USER=exim
+	MAIL_USER=exim
 fi
 
 # Additional argument formatting
@@ -56,17 +56,17 @@ is_system_enabled "$MAIL_SYSTEM" 'MAIL_SYSTEM'
 is_object_valid 'user' 'USER' "$user"
 is_object_unsuspended 'user' 'USER' "$user"
 
-if [ "$($BIN/v-list-mail-domain $user $domain_utf plain |cut -f 1) " != "$domain" ]; then
-    is_domain_new 'mail' "$domain_utf"
+if [ "$($BIN/v-list-mail-domain $user $domain_utf plain | cut -f 1) " != "$domain" ]; then
+	is_domain_new 'mail' "$domain_utf"
 fi
-if [ "$($BIN/v-list-mail-domain $user $domain_idn plain |cut -f 1) " != "$domain" ]; then
-    is_domain_new 'mail' "$domain_idn"
+if [ "$($BIN/v-list-mail-domain $user $domain_idn plain | cut -f 1) " != "$domain" ]; then
+	is_domain_new 'mail' "$domain_idn"
 else
-    is_domain_new 'mail' "$domain"
+	is_domain_new 'mail' "$domain"
 fi
 if [ -z "$(is_ip_format_valid $domain)" ]; then
-    echo "Error: Invalid domain format. IP address detected as input."
-    exit 1
+	echo "Error: Invalid domain format. IP address detected as input."
+	exit 1
 fi
 
 is_package_full 'MAIL_DOMAINS'
@@ -85,10 +85,10 @@ source_conf "$USER_DATA/user.conf"
 # Inherit web domain local ip address
 domain_ip=$(get_object_value 'web' 'DOMAIN' "$domain" '$IP')
 if [ ! -z "$domain_ip" ]; then
-    local_ip=$(get_real_ip "$domain_ip")
-    is_ip_valid "$local_ip" "$user"
+	local_ip=$(get_real_ip "$domain_ip")
+	is_ip_valid "$local_ip" "$user"
 else
-    get_user_ip
+	get_user_ip
 fi
 
 # Generating timestamp
@@ -105,9 +105,9 @@ syshealth_repair_mail_config
 
 # Generating DKIM keys
 if [ "$dkim" = 'yes' ]; then
-    openssl genrsa -out $USER_DATA/mail/$domain.pem $dkim_size &>/dev/null
-    openssl rsa -pubout -in $USER_DATA/mail/$domain.pem \
-        -out $USER_DATA/mail/$domain.pub &>/dev/null
+	openssl genrsa -out $USER_DATA/mail/$domain.pem $dkim_size &> /dev/null
+	openssl rsa -pubout -in $USER_DATA/mail/$domain.pem \
+		-out $USER_DATA/mail/$domain.pub &> /dev/null
 fi
 
 # Set permissions
@@ -116,78 +116,78 @@ chmod 660 $USER_DATA/mail.conf
 
 # Building exim configs
 if [[ "$MAIL_SYSTEM" =~ exim ]]; then
-    mkdir $HOMEDIR/$user/conf/mail/$domain
-    mkdir $HOMEDIR/$user/mail/$domain_idn
-    touch $HOMEDIR/$user/conf/mail/$domain/aliases
-    touch $HOMEDIR/$user/conf/mail/$domain/passwd
-    touch $HOMEDIR/$user/conf/mail/$domain/fwd_only
-    touch $HOMEDIR/$user/conf/mail/$domain/accounts
-    ln -s $HOMEDIR/$user/conf/mail/$domain \
-        /etc/$MAIL_SYSTEM/domains/$domain_idn
+	mkdir $HOMEDIR/$user/conf/mail/$domain
+	mkdir $HOMEDIR/$user/mail/$domain_idn
+	touch $HOMEDIR/$user/conf/mail/$domain/aliases
+	touch $HOMEDIR/$user/conf/mail/$domain/passwd
+	touch $HOMEDIR/$user/conf/mail/$domain/fwd_only
+	touch $HOMEDIR/$user/conf/mail/$domain/accounts
+	ln -s $HOMEDIR/$user/conf/mail/$domain \
+		/etc/$MAIL_SYSTEM/domains/$domain_idn
 
-    # Seeting outgoing ip address
-    if [ -n "$local_ip" ]; then
-        echo "$local_ip" > $HOMEDIR/$user/conf/mail/$domain/ip
-    fi
+	# Seeting outgoing ip address
+	if [ -n "$local_ip" ]; then
+		echo "$local_ip" > $HOMEDIR/$user/conf/mail/$domain/ip
+	fi
 
-    if [ -n "$ANTISPAM_SYSTEM" ]; then
-        # Adding antispam protection
-        if [ "$antispam" = 'yes' ]; then
-            touch "$HOMEDIR/$user/conf/mail/$domain/antispam"
-        fi
-        if [ "$reject" = 'yes' ]; then
-            touch "$HOMEDIR/$user/conf/mail/$domain/reject_spam"
-        fi
-    fi
+	if [ -n "$ANTISPAM_SYSTEM" ]; then
+		# Adding antispam protection
+		if [ "$antispam" = 'yes' ]; then
+			touch "$HOMEDIR/$user/conf/mail/$domain/antispam"
+		fi
+		if [ "$reject" = 'yes' ]; then
+			touch "$HOMEDIR/$user/conf/mail/$domain/reject_spam"
+		fi
+	fi
 
-    if [ -n "$ANTIVIRUS_SYSTEM" ]; then
-        # Adding antivirus protection
-        if [ "$antivirus" = 'yes' ]; then
-            touch "$HOMEDIR/$user/conf/mail/$domain/antivirus"
-        fi
-    fi
+	if [ -n "$ANTIVIRUS_SYSTEM" ]; then
+		# Adding antivirus protection
+		if [ "$antivirus" = 'yes' ]; then
+			touch "$HOMEDIR/$user/conf/mail/$domain/antivirus"
+		fi
+	fi
 
-    # Adding dkim support
-    if [ "$dkim" = 'yes' ]; then
-        cp -f $USER_DATA/mail/$domain.pem \
-            $HOMEDIR/$user/conf/mail/$domain/dkim.pem
-    fi
+	# Adding dkim support
+	if [ "$dkim" = 'yes' ]; then
+		cp -f $USER_DATA/mail/$domain.pem \
+			$HOMEDIR/$user/conf/mail/$domain/dkim.pem
+	fi
 
-    # Set permission
-    chmod 771 $HOMEDIR/$user/conf/mail/$domain
-    chmod 660 $HOMEDIR/$user/conf/mail/$domain/*
-    chmod 771 /etc/$MAIL_SYSTEM/domains/$domain_idn
-    chmod 770 $HOMEDIR/$user/mail/$domain_idn
+	# Set permission
+	chmod 771 $HOMEDIR/$user/conf/mail/$domain
+	chmod 660 $HOMEDIR/$user/conf/mail/$domain/*
+	chmod 771 /etc/$MAIL_SYSTEM/domains/$domain_idn
+	chmod 770 $HOMEDIR/$user/mail/$domain_idn
 
-    # Set ownership
-    chown -R $MAIL_USER:mail $HOMEDIR/$user/conf/mail/$domain
-    if [ "$IMAP_SYSTEM" = 'dovecot' ]; then
-        chown -R dovecot:mail $HOMEDIR/$user/conf/mail/$domain/passwd
-    fi
-    chown $MAIL_USER:mail $HOMEDIR/$user/conf/mail/$domain/accounts
-    chown $user:mail $HOMEDIR/$user/mail/$domain_idn
+	# Set ownership
+	chown -R $MAIL_USER:mail $HOMEDIR/$user/conf/mail/$domain
+	if [ "$IMAP_SYSTEM" = 'dovecot' ]; then
+		chown -R dovecot:mail $HOMEDIR/$user/conf/mail/$domain/passwd
+	fi
+	chown $MAIL_USER:mail $HOMEDIR/$user/conf/mail/$domain/accounts
+	chown $user:mail $HOMEDIR/$user/mail/$domain_idn
 fi
 
 # Adding dkim dns records
 if [ -n "$DNS_SYSTEM" ] && [ "$dkim" = 'yes' ]; then
-    check_dns_domain=$(is_object_valid 'dns' 'DOMAIN' "$domain")
-    if [ "$?" -eq 0 ]; then
-        p=$(cat $USER_DATA/mail/$domain.pub|grep -v ' KEY---'|tr -d '\n')
-        record='_domainkey'
-        policy="\"t=y; o=~;\""
-        $BIN/v-add-dns-record "$user" "$domain" "$record" TXT "$policy" '' '' 'no' '' 'yes'
+	check_dns_domain=$(is_object_valid 'dns' 'DOMAIN' "$domain")
+	if [ "$?" -eq 0 ]; then
+		p=$(cat $USER_DATA/mail/$domain.pub | grep -v ' KEY---' | tr -d '\n')
+		record='_domainkey'
+		policy="\"t=y; o=~;\""
+		$BIN/v-add-dns-record "$user" "$domain" "$record" TXT "$policy" '' '' 'no' '' 'yes'
 
-        record='mail._domainkey'
-        selector="\"v=DKIM1\; k=rsa\; p=$p\""
-        $BIN/v-add-dns-record "$user" "$domain" "$record" TXT "$selector" '' '' 'yes' '' 'yes'
-    fi
+		record='mail._domainkey'
+		selector="\"v=DKIM1\; k=rsa\; p=$p\""
+		$BIN/v-add-dns-record "$user" "$domain" "$record" TXT "$selector" '' '' 'yes' '' 'yes'
+	fi
 fi
 
 # Add webmail configuration to mail domain
 if [ -n "$WEB_SYSTEM" ] || [ -n "$PROXY_SYSTEM" ]; then
-    if [ -n "$IMAP_SYSTEM" ]; then
-        $BIN/v-add-mail-domain-webmail "$user" "$domain" '' 'no'
-    fi
+	if [ -n "$IMAP_SYSTEM" ]; then
+		$BIN/v-add-mail-domain-webmail "$user" "$domain" '' 'no'
+	fi
 fi
 
 #----------------------------------------------------------#
@@ -198,16 +198,16 @@ fi
 increase_user_value "$user" '$U_MAIL_DOMAINS'
 
 if [ "$dkim" = 'yes' ]; then
-    increase_user_value "$user" '$U_MAIL_DKIM'
+	increase_user_value "$user" '$U_MAIL_DKIM'
 fi
 
 # Restarting web server
 $BIN/v-restart-web "$restart"
-check_result $? "Web restart failed" >/dev/null
+check_result $? "Web restart failed" > /dev/null
 
 # Restarting proxy server
 $BIN/v-restart-proxy "$restart"
-check_result $? "Proxy restart failed" >/dev/null
+check_result $? "Proxy restart failed" > /dev/null
 
 # Logging
 $BIN/v-log-action "$user" "Info" "Mail" "Added new mail domain ($domain)."
diff --git a/bin/v-add-sys-filemanager b/bin/v-add-sys-filemanager
--- a/bin/v-add-sys-filemanager
+++ b/bin/v-add-sys-filemanager
@@ -33,27 +33,27 @@ COMPOSER_BIN="$HOMEDIR/$user/.composer/composer"
 
 # Checking root permissions
 if [ "x$(id -u)" != 'x0' ]; then
-    echo "ERROR: v-add-sys-filemanager can be run executed only by root user"
-    exit 10
+	echo "ERROR: v-add-sys-filemanager can be run executed only by root user"
+	exit 10
 fi
 
 # Ensure that $HESTIA (/usr/local/hestia/) and other variables are valid.
 if [ -z "$HESTIA" ]; then
-    HESTIA="/usr/local/hestia"
+	HESTIA="/usr/local/hestia"
 fi
 
 if [ -z "$HOMEDIR" ] || [ -z "$HESTIA_INSTALL_DIR" ]; then
-    echo "ERROR: Environment variables not present, installation aborted."
-    exit 2
+	echo "ERROR: Environment variables not present, installation aborted."
+	exit 2
 fi
 
 # Ensure that Composer is installed for the user before continuing as it is a dependency of the File Manager.
 if [ ! -f "$COMPOSER_BIN" ]; then
-    $BIN/v-add-user-composer "$user"
-    if [ $? -ne 0 ]; then
-        $BIN/v-add-user-notification admin 'Composer installation failed!' '<b>The File Manager will not work without Composer.</b><br><br>Please try running the installer manually from a shell session:<br>v-add-sys-filemanager<br><br>If this continues, open an issue report on <a href="https://github.com/hestiacp/hestiacp/issues" target="_new"><i class="fab fa-github"></i> GitHub</a>.'
-        exit 1
-    fi
+	$BIN/v-add-user-composer "$user"
+	if [ $? -ne 0 ]; then
+		$BIN/v-add-user-notification admin 'Composer installation failed!' '<b>The File Manager will not work without Composer.</b><br><br>Please try running the installer manually from a shell session:<br>v-add-sys-filemanager<br><br>If this continues, open an issue report on <a href="https://github.com/hestiacp/hestiacp/issues" target="_new"><i class="fab fa-github"></i> GitHub</a>.'
+		exit 1
+	fi
 fi
 
 # Perform verification if read-only mode is enabled
@@ -63,7 +63,7 @@ check_hestia_demo_mode
 #                       Action                             #
 #----------------------------------------------------------#
 
-openssl_installed=$(/usr/local/hestia/php/bin/php -m | grep openssl);
+openssl_installed=$(/usr/local/hestia/php/bin/php -m | grep openssl)
 
 rm --recursive --force "$FM_INSTALL_DIR"
 mkdir -p "$FM_INSTALL_DIR"
@@ -80,23 +80,23 @@ cp --recursive --force ${HESTIA_INSTALL_DIR}/filemanager/filegator/* "${FM_INSTA
 
 chown $user: -R "${FM_INSTALL_DIR}"
 
-if [ -z "$openssl_installed"  ]; then
-    COMPOSER_HOME="$HOMEDIR/$user/.config/composer" user_exec /usr/bin/php $COMPOSER_BIN --quiet --no-dev install
+if [ -z "$openssl_installed" ]; then
+	COMPOSER_HOME="$HOMEDIR/$user/.config/composer" user_exec /usr/bin/php $COMPOSER_BIN --quiet --no-dev install
 else
-    COMPOSER_HOME="$HOMEDIR/$user/.config/composer" user_exec /usr/local/hestia/php/bin/php $COMPOSER_BIN --quiet --no-dev install
+	COMPOSER_HOME="$HOMEDIR/$user/.config/composer" user_exec /usr/local/hestia/php/bin/php $COMPOSER_BIN --quiet --no-dev install
 fi
 
 # Check if installation was successful, if not abort script and throw error message notification and clean-up
 if [ $? -ne 0 ]; then
-    echo "ERROR: File Manager installation failed!"
-    echo "Please report this to our development team:"
-    echo "https://github.com/hestiacp/hestiacp/issues"
-    $BIN/v-add-user-notification admin 'File Manager installation failed!' 'Please report this to our development team on <a href="https://github.com/hestiacp/hestiacp/issues" target="_new"><i class="fab fa-github"></i> GitHub</a>.'
-    # Installation failed, clean up files
-    rm --recursive --force ${FM_INSTALL_DIR}
-    $BIN/v-change-sys-config-value 'FILE_MANAGER' 'false'
-    $BIN/v-log-action "system" "Error" "Plugins" "File Manager installation failed (Version: $fm_v)."
-    exit 1
+	echo "ERROR: File Manager installation failed!"
+	echo "Please report this to our development team:"
+	echo "https://github.com/hestiacp/hestiacp/issues"
+	$BIN/v-add-user-notification admin 'File Manager installation failed!' 'Please report this to our development team on <a href="https://github.com/hestiacp/hestiacp/issues" target="_new"><i class="fab fa-github"></i> GitHub</a>.'
+	# Installation failed, clean up files
+	rm --recursive --force ${FM_INSTALL_DIR}
+	$BIN/v-change-sys-config-value 'FILE_MANAGER' 'false'
+	$BIN/v-log-action "system" "Error" "Plugins" "File Manager installation failed (Version: $fm_v)."
+	exit 1
 fi
 
 # Add configuration file
diff --git a/bin/v-add-web-domain-ftp b/bin/v-add-web-domain-ftp
--- a/bin/v-add-web-domain-ftp
+++ b/bin/v-add-web-domain-ftp
@@ -15,7 +15,8 @@ user=$1
 domain=$2
 domain_idn=$2
 ftp_user=${1}_${3}
-password=$4; HIDE=4
+password=$4
+HIDE=4
 ftp_path=$5
 
 # Includes
@@ -46,9 +47,9 @@ is_object_valid 'web' 'DOMAIN' "$domain"
 is_object_unsuspended 'web' 'DOMAIN' "$domain"
 check_ftp_user=$(grep "^$ftp_user:" /etc/passwd)
 if [ -n "$check_ftp_user" ] && [ "$FTP_USER" != "$ftp_user" ]; then
-    echo "Error: ftp user $ftp_user already exists"
-    log_event "$E_EXISTS" "$ARGUMENTS"
-    exit "$E_EXISTS"
+	echo "Error: ftp user $ftp_user already exists"
+	log_event "$E_EXISTS" "$ARGUMENTS"
+	exit "$E_EXISTS"
 fi
 is_password_valid
 
@@ -65,44 +66,44 @@ get_domain_values 'web'
 # Defining ftp user shell
 shell=$(which nologin)
 if [ -n "$FTP_SHELL" ]; then
-    shell=$FTP_SHELL
+	shell=$FTP_SHELL
 fi
 
 # Defining path
 if [ -z "$ftp_path" ]; then
-    ftp_path_a="$HOMEDIR/$user/web/$domain"
+	ftp_path_a="$HOMEDIR/$user/web/$domain"
 else
-    # Validating absolute path
-    ftp_path_a=$(readlink -f "$HOMEDIR/$user/web/$domain/$ftp_path")
-    if [ -z "$(echo $ftp_path_a |grep $HOMEDIR/$user/web/$domain)" ]; then
-        echo "Error: absolute path $ftp_path_a is invalid"
-        log_event "$E_INVALID" "$ARGUMENTS"
-        exit "$E_INVALID"
-    fi
-    # Creating ftp user home directory
-    if [ ! -e "$ftp_path_a" ]; then
-        $BIN/v-add-fs-directory "$user" "$ftp_path_a"
-        chown $user:$user "$ftp_path_a"
-        chmod 751 "$ftp_path_a"
-    fi
+	# Validating absolute path
+	ftp_path_a=$(readlink -f "$HOMEDIR/$user/web/$domain/$ftp_path")
+	if [ -z "$(echo $ftp_path_a | grep $HOMEDIR/$user/web/$domain)" ]; then
+		echo "Error: absolute path $ftp_path_a is invalid"
+		log_event "$E_INVALID" "$ARGUMENTS"
+		exit "$E_INVALID"
+	fi
+	# Creating ftp user home directory
+	if [ ! -e "$ftp_path_a" ]; then
+		$BIN/v-add-fs-directory "$user" "$ftp_path_a"
+		chown $user:$user "$ftp_path_a"
+		chmod 751 "$ftp_path_a"
+	fi
 fi
 
 # Adding ftp user
 /usr/sbin/useradd $ftp_user \
-    -s $shell \
-    -o -u $(id -u $user) \
-    -g $(id -g $user) \
-    -G hestia-users \
-    -M -d "$ftp_path_a"  > /dev/null 2>&1
+	-s $shell \
+	-o -u $(id -u $user) \
+	-g $(id -g $user) \
+	-G hestia-users \
+	-M -d "$ftp_path_a" > /dev/null 2>&1
 
 # Set ftp user password
 echo "$ftp_user:$password" | /usr/sbin/chpasswd
 
 if [ $? -ne 0 ]; then
-    # Delete user on failure again
-    /usr/sbin/deluser "$ftp_user"  > /dev/null 2>&1
-    echo "Error: Password not accepted due to PAM restrictions"
-    exit 2
+	# Delete user on failure again
+	/usr/sbin/deluser "$ftp_user" > /dev/null 2>&1
+	echo "Error: Password not accepted due to PAM restrictions"
+	exit 2
 fi
 
 ftp_md5=$(awk -v user=$ftp_user -F : 'user == $1 {print $2}' /etc/shadow)
@@ -115,13 +116,13 @@ $BIN/v-add-user-sftp-jail "$ftp_user"
 #----------------------------------------------------------#
 
 # Transforming absolute path to relative
-ftp_path_r=$(echo $ftp_path_a |sed "s%$HOMEDIR/$user/web/$domain%%")
+ftp_path_r=$(echo $ftp_path_a | sed "s%$HOMEDIR/$user/web/$domain%%")
 
 # Concatenating ftp variables
 if [ ! -z "$FTP_USER" ]; then
-    ftp_user="$FTP_USER:$ftp_user"
-    ftp_md5="$FTP_MD5:$ftp_md5"
-    ftp_path="$FTP_PATH:$ftp_path_r"
+	ftp_user="$FTP_USER:$ftp_user"
+	ftp_md5="$FTP_MD5:$ftp_md5"
+	ftp_path="$FTP_PATH:$ftp_path_r"
 fi
 
 # Adding new key into web.conf
diff --git a/bin/v-change-database-owner b/bin/v-change-database-owner
--- a/bin/v-change-database-owner
+++ b/bin/v-change-database-owner
@@ -14,7 +14,6 @@
 database=$1
 user=$2
 
-
 # Includes
 # shellcheck source=/etc/hestiacp/hestia.conf
 source /etc/hestiacp/hestia.conf
@@ -40,39 +39,39 @@ is_object_unsuspended 'user' 'USER' "$user"
 # Check owner existance
 owner=$(echo $database | cut -f 1 -d '_')
 if [ ! -d "$HESTIA/data/users/$owner" ]; then
-    echo "Error: database owner doesn't exist"
-    log_event "$E_NOTEXIST" "$ARGUMENTS"
-    exit "$E_NOTEXIST"
+	echo "Error: database owner doesn't exist"
+	log_event "$E_NOTEXIST" "$ARGUMENTS"
+	exit "$E_NOTEXIST"
 fi
 
 # Check if owner is the same as the dst user
 if [ "$owner" = "$user" ]; then
-    exit
+	exit
 fi
 
 # Check db existance
 db_data=$(grep "DB='$database'" $HESTIA/data/users/$owner/db.conf)
 if [ -z "$db_data" ]; then
-    echo "Error: database $database doesn't exist"
-    log_event "$E_NOTEXIST" "$ARGUMENTS"
-    exit "$E_NOTEXIST"
+	echo "Error: database $database doesn't exist"
+	log_event "$E_NOTEXIST" "$ARGUMENTS"
+	exit "$E_NOTEXIST"
 fi
 
 parse_object_kv_list "$db_data"
 #Fix issue #1084 with "Upper case not allowed with PGSQL"
 if [ "$TYPE" == "pgsql" ]; then
-   usersmall=$(echo "$user" | tr '[:upper:]' '[:lower:]');
+	usersmall=$(echo "$user" | tr '[:upper:]' '[:lower:]')
 else
-   usersmall=$user
+	usersmall=$user
 fi
 
 # Check if database name is uniqe
 new_db=$(echo $database | sed "s/^${owner}_/${usersmall}_/")
 check_db=$(grep "DB='$new_db'" $HESTIA/data/users/$user/db.conf)
 if [ -n "$check_db" ]; then
-    echo "Error: $new_db database exists"
-    log_event "$E_EXISTS" "$ARGUMENTS"
-    exit "$E_EXISTS"
+	echo "Error: $new_db database exists"
+	log_event "$E_EXISTS" "$ARGUMENTS"
+	exit "$E_EXISTS"
 fi
 
 # Perform verification if read-only mode is enabled
@@ -92,8 +91,8 @@ $BIN/v-suspend-database $owner $database > /dev/null 2>&1
 dump="$tmpdir/$database.$TYPE.sql"
 grants="$tmpdir/$database.$TYPE.$DBUSER"
 case $TYPE in
-    mysql) dump_mysql_database ;;
-    pgsql) dump_pgsql_database ;;
+	mysql) dump_mysql_database ;;
+	pgsql) dump_pgsql_database ;;
 esac
 
 # Import configuration
@@ -109,8 +108,8 @@ $BIN/v-rebuild-databases "$user"
 
 # Import dump
 case $TYPE in
-    mysql) import_mysql_database "$dump" ;;
-    pgsql) import_pgsql_database "$dump" ;;
+	mysql) import_mysql_database "$dump" ;;
+	pgsql) import_pgsql_database "$dump" ;;
 esac
 
 # Deleting tmpdir
diff --git a/bin/v-change-sys-language b/bin/v-change-sys-language
--- a/bin/v-change-sys-language
+++ b/bin/v-change-sys-language
@@ -22,13 +22,12 @@ source $HESTIA/func/main.sh
 # load config file
 source_conf "$HESTIA/conf/hestia.conf"
 
-
 is_language_valid() {
-    if [ ! -d "$HESTIA/web/locale/$language" ]; then
-        echo "Error: language file $language doesn't exist"
-        log_event "$E_NOTEXIST $ARGUMENTS"
-        exit "$E_NOTEXIST"
-    fi
+	if [ ! -d "$HESTIA/web/locale/$language" ]; then
+		echo "Error: language file $language doesn't exist"
+		log_event "$E_NOTEXIST $ARGUMENTS"
+		exit "$E_NOTEXIST"
+	fi
 }
 
 #----------------------------------------------------------#
@@ -48,16 +47,16 @@ check_hestia_demo_mode
 
 # Change language
 if [ -z "$(grep LANGUAGE $HESTIA/conf/hestia.conf)" ]; then
-    echo "LANGUAGE='$language'" >> $HESTIA/conf/hestia.conf
+	echo "LANGUAGE='$language'" >> $HESTIA/conf/hestia.conf
 else
-    sed -i "s/LANGUAGE=.*/LANGUAGE='$language'/g" $HESTIA/conf/hestia.conf
+	sed -i "s/LANGUAGE=.*/LANGUAGE='$language'/g" $HESTIA/conf/hestia.conf
 fi
 
 # Update language for all existing users if specified
 if [ "$update_users" = "yes" ]; then
-    for user in $($HESTIA/bin/v-list-sys-users plain); do
-        $BIN/v-change-user-language "$user" "$language"
-    done
+	for user in $($HESTIA/bin/v-list-sys-users plain); do
+		$BIN/v-change-user-language "$user" "$language"
+	done
 fi
 
 #----------------------------------------------------------#
diff --git a/bin/v-change-web-domain-ftp-password b/bin/v-change-web-domain-ftp-password
--- a/bin/v-change-web-domain-ftp-password
+++ b/bin/v-change-web-domain-ftp-password
@@ -15,7 +15,8 @@ user=$1
 domain=$2
 domain_idn=$2
 ftp_user=$3
-password=$4; HIDE=4
+password=$4
+HIDE=4
 
 # Includes
 # shellcheck source=/etc/hestiacp/hestia.conf
@@ -46,9 +47,9 @@ is_object_unsuspended 'web' 'DOMAIN' "$domain"
 is_password_valid
 get_domain_values 'web'
 if [ -z "$(echo $FTP_USER | tr ':' '\n' | grep ^$ftp_user$)" ]; then
-    echo "Error: account $ftp_user doesn't exist"
-    log_event "$E_NOTEXIST" "$ARGUMENTS"
-    exit "$E_NOTEXIST"
+	echo "Error: account $ftp_user doesn't exist"
+	log_event "$E_NOTEXIST" "$ARGUMENTS"
+	exit "$E_NOTEXIST"
 fi
 
 # Perform verification if read-only mode is enabled
@@ -62,8 +63,8 @@ check_hestia_demo_mode
 echo "$ftp_user:$password" | /usr/sbin/chpasswd
 
 if [ $? -ne 0 ]; then
-    echo "Error: Password not accepted due to PAM restrictions"
-    exit 2
+	echo "Error: Password not accepted due to PAM restrictions"
+	exit 2
 fi
 
 ftp_md5=$(awk -v user=$ftp_user -F : 'user == $1 {print $2}' /etc/shadow)
@@ -73,11 +74,11 @@ ftp_md5=$(awk -v user=$ftp_user -F : 'user == $1 {print $2}' /etc/shadow)
 #----------------------------------------------------------#
 
 # Rebuilding FTP variables
-position=$(echo $FTP_USER |tr ':' '\n' |grep -n '' |grep ":$ftp_user$" |\
-    cut -f 1 -d:)
-ftp_md5=$(echo $FTP_MD5 |tr ':' '\n' |grep -n '' |\
-    sed -e "s%^$position:.*%$position:$ftp_md5%" |\
-    cut -f 2 -d :| sed -e "/^$/d"| sed -e ':a;N;$!ba;s/\n/:/g')
+position=$(echo $FTP_USER | tr ':' '\n' | grep -n '' | grep ":$ftp_user$" \
+	| cut -f 1 -d:)
+ftp_md5=$(echo $FTP_MD5 | tr ':' '\n' | grep -n '' \
+	| sed -e "s%^$position:.*%$position:$ftp_md5%" \
+	| cut -f 2 -d : | sed -e "/^$/d" | sed -e ':a;N;$!ba;s/\n/:/g')
 
 # Updating config
 update_object_value 'web' 'DOMAIN' "$domain" '$FTP_MD5' "$ftp_md5"
diff --git a/bin/v-change-web-domain-ftp-path b/bin/v-change-web-domain-ftp-path
--- a/bin/v-change-web-domain-ftp-path
+++ b/bin/v-change-web-domain-ftp-path
@@ -45,15 +45,15 @@ is_object_valid 'web' 'DOMAIN' "$domain"
 is_object_unsuspended 'web' 'DOMAIN' "$domain"
 get_domain_values 'web'
 if [ -z "$(echo $FTP_USER | tr ':' '\n' | grep ^$ftp_user$)" ]; then
-    echo "Error: account $ftp_user doesn't exist"
-    log_event "$E_NOTEXIST" "$ARGUMENTS"
-    exit "$E_NOTEXIST"
+	echo "Error: account $ftp_user doesn't exist"
+	log_event "$E_NOTEXIST" "$ARGUMENTS"
+	exit "$E_NOTEXIST"
 fi
 ftp_path_a=$(readlink -f "$HOMEDIR/$user/web/$domain/$ftp_path")
-if [ -z "$(echo $ftp_path_a |grep $HOMEDIR/$user/web/$domain)" ]; then
-    echo "Error: absolute path $ftp_path_a is invalid"
-    log_event "$E_INVALID" "$ARGUMENTS"
-    exit "$E_INVALID"
+if [ -z "$(echo $ftp_path_a | grep $HOMEDIR/$user/web/$domain)" ]; then
+	echo "Error: absolute path $ftp_path_a is invalid"
+	log_event "$E_INVALID" "$ARGUMENTS"
+	exit "$E_INVALID"
 fi
 
 # Perform verification if read-only mode is enabled
@@ -65,9 +65,9 @@ check_hestia_demo_mode
 
 # MKDIR if path doesn't exist
 if [ ! -e "$ftp_path_a" ]; then
-    $BIN/v-add-fs-directory "$user" "$ftp_path_a"
-    chown $user:$user "$ftp_path_a"
-    chmod 751 "$ftp_path_a"
+	$BIN/v-add-fs-directory "$user" "$ftp_path_a"
+	chown $user:$user "$ftp_path_a"
+	chmod 751 "$ftp_path_a"
 fi
 
 # Chaning ftp user path
@@ -81,14 +81,14 @@ sed -i "$str s%$old_path%$ftp_path_a%g" /etc/passwd
 #----------------------------------------------------------#
 
 # Transforming absolute path to relative
-ftp_path_r=$(echo $ftp_path_a |sed "s%$HOMEDIR/$user/web/$domain%%")
+ftp_path_r=$(echo $ftp_path_a | sed "s%$HOMEDIR/$user/web/$domain%%")
 
 # Rebuilding FTP variables
-position=$(echo $FTP_USER |tr ':' '\n' |grep -n '' |grep ":$ftp_user$" |\
-    cut -f 1 -d:)
-ftp_path=$(echo $FTP_PATH |tr ':' '\n' |grep -n '' |\
-    sed -e "s%^$position:.*%$position:$ftp_path_r%" |\
-    cut -f 2 -d :| sed -e ':a;N;$!ba;s/\n/:/g')
+position=$(echo $FTP_USER | tr ':' '\n' | grep -n '' | grep ":$ftp_user$" \
+	| cut -f 1 -d:)
+ftp_path=$(echo $FTP_PATH | tr ':' '\n' | grep -n '' \
+	| sed -e "s%^$position:.*%$position:$ftp_path_r%" \
+	| cut -f 2 -d : | sed -e ':a;N;$!ba;s/\n/:/g')
 
 # Updating config
 update_object_value 'web' 'DOMAIN' "$domain" '$FTP_PATH' "$ftp_path"
diff --git a/bin/v-copy-user-package b/bin/v-copy-user-package
--- a/bin/v-copy-user-package
+++ b/bin/v-copy-user-package
@@ -38,24 +38,24 @@ is_object_format_valid "$package" "Package"
 is_object_format_valid "$new_package" "New package"
 
 if [ -n "$1" ]; then
-    if [ ! -f "$HESTIA/data/packages/$package.pkg" ]; then
-        echo "Error: package does not exist."
-        exit "$E_NOTEXIST"
-    fi
-    if [ -n "$2" ]; then
-        # Copy package
-        cp -f "$HESTIA/data/packages/$package.pkg" "$HESTIA/data/packages/$new_package.pkg"
-        # Don't leave the .sh file behind
-        if [ -f "$HESTIA/data/packages/$package.sh" ]; then
-            cp $HESTIA/data/packages/$package.sh $HESTIA/data/packages/$new_package.sh
-        fi
-    else
-        echo "Error: new package name not specified."
-        exit "$E_ARGS"
-    fi
+	if [ ! -f "$HESTIA/data/packages/$package.pkg" ]; then
+		echo "Error: package does not exist."
+		exit "$E_NOTEXIST"
+	fi
+	if [ -n "$2" ]; then
+		# Copy package
+		cp -f "$HESTIA/data/packages/$package.pkg" "$HESTIA/data/packages/$new_package.pkg"
+		# Don't leave the .sh file behind
+		if [ -f "$HESTIA/data/packages/$package.sh" ]; then
+			cp $HESTIA/data/packages/$package.sh $HESTIA/data/packages/$new_package.sh
+		fi
+	else
+		echo "Error: new package name not specified."
+		exit "$E_ARGS"
+	fi
 else
-    echo "Error: package name not specified."
-    exit "$E_ARGS"
+	echo "Error: package name not specified."
+	exit "$E_ARGS"
 fi
 
 #----------------------------------------------------------#
diff --git a/bin/v-unsuspend-domain b/bin/v-unsuspend-domain
--- a/bin/v-unsuspend-domain
+++ b/bin/v-unsuspend-domain
@@ -40,39 +40,39 @@ check_hestia_demo_mode
 
 # Working on Web domain
 if [ -n "$WEB_SYSTEM" ]; then
-    str=$(grep "DOMAIN='$domain'" $USER_DATA/web.conf |grep "SUSPENDED='yes")
-    if [  -n "$str" ]; then
-        domain_found='yes'
-        $BIN/v-unsuspend-web-domain "$user" "$domain" 'no'
-        check_result $? "can't suspend web" > /dev/null
-    fi
+	str=$(grep "DOMAIN='$domain'" $USER_DATA/web.conf | grep "SUSPENDED='yes")
+	if [ -n "$str" ]; then
+		domain_found='yes'
+		$BIN/v-unsuspend-web-domain "$user" "$domain" 'no'
+		check_result $? "can't suspend web" > /dev/null
+	fi
 fi
 
 # Working on DNS domain
 if [ -n "$DNS_SYSTEM" ]; then
-    str=$(grep "DOMAIN='$domain'" $USER_DATA/dns.conf |grep "SUSPENDED='yes")
-    if [  -n "$str" ]; then
-        domain_found='yes'
-        $BIN/v-unsuspend-dns-domain "$user" "$domain" 'no'
-        check_result $? "can't suspend dns" > /dev/null
-    fi
+	str=$(grep "DOMAIN='$domain'" $USER_DATA/dns.conf | grep "SUSPENDED='yes")
+	if [ -n "$str" ]; then
+		domain_found='yes'
+		$BIN/v-unsuspend-dns-domain "$user" "$domain" 'no'
+		check_result $? "can't suspend dns" > /dev/null
+	fi
 fi
 
 # Working on Mail domain
 if [ -n "$MAIL_SYSTEM" ]; then
-    str=$(grep "DOMAIN='$domain'" $USER_DATA/mail.conf |grep "SUSPENDED='yes")
-    if [  -n "$str" ]; then
-        domain_found='yes'
-        $BIN/v-unsuspend-mail-domain "$user" "$domain" "no"
-        check_result $? "can't suspend mail" > /dev/null
-    fi
+	str=$(grep "DOMAIN='$domain'" $USER_DATA/mail.conf | grep "SUSPENDED='yes")
+	if [ -n "$str" ]; then
+		domain_found='yes'
+		$BIN/v-unsuspend-mail-domain "$user" "$domain" "no"
+		check_result $? "can't suspend mail" > /dev/null
+	fi
 fi
 
 # Checking domain search result
 if [ -z "$domain_found" ]; then
-    echo "Error: domain $domain doesn't exist"
-    log_event "$E_NOTEXIST" "$ARGUMENTS"
-    exit $E_NOTEXIST
+	echo "Error: domain $domain doesn't exist"
+	log_event "$E_NOTEXIST" "$ARGUMENTS"
+	exit $E_NOTEXIST
 fi
 
 # Restarting services
