Improved file manager API functions

diff --git a/bin/v-add-fs-file b/bin/v-add-fs-file
--- a/bin/v-add-fs-file
+++ b/bin/v-add-fs-file
@@ -15,23 +15,30 @@ fi
 
 # Checking vesta user
 if [ ! -e "$VESTA/data/users/$user" ]; then
-    exit 1
+    echo "Error: vesta user $user doesn't exist"
+    exit 3
 fi
 
 # Checking user homedir
 homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z $homedir ]; then
-    exit 1
+    echo "Error: user home directory doesn't exist"
+    exit 12
 fi
 
 # Checking destination path
 rpath=$(readlink -f "$dst_file")
 if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-    exit 1
+    echo "Error: invalid destination path $dst_dir"
+    exit 2
 fi
 
 # Creating file
-sudo -u $user touch $dst_file >/dev/null 2>&1
+sudo -u $user touch "$dst_file" >/dev/null 2>&1
+if [ $? -ne 0 ]; then 
+    echo "Error: file $dst_file was not created"
+    exit 3
+fi
 
 # Exiting
-exit $?
+exit
diff --git a/bin/v-delete-fs-directory b/bin/v-delete-fs-directory
--- a/bin/v-delete-fs-directory
+++ b/bin/v-delete-fs-directory
@@ -16,23 +16,30 @@ fi
 
 # Checking vesta user
 if [ ! -e "$VESTA/data/users/$user" ]; then
-    exit 1
+    echo "Error: vesta user $user doesn't exist"
+    exit 3
 fi
 
 # Checking user homedir
 homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z $homedir ]; then
-    exit 1
+    echo "Error: user home directory doesn't exist"
+    exit 12
 fi
 
 # Checking destination path
 rpath=$(readlink -f "$dst_dir")
 if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
+    echo "Error: invalid destination path $dst_dir"
     exit 1
 fi
 
 # Deleting directory
-sudo -u $user rm -rf $dst_dir >/dev/null 2>&1
+sudo -u $user rm -rf "$dst_dir" # >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: directory $dst_dir was not deleted"
+    exit 3
+fi
 
 # Exiting
-exit $?
+exit
diff --git a/bin/v-extract-fs-archive b/bin/v-extract-fs-archive
--- a/bin/v-extract-fs-archive
+++ b/bin/v-extract-fs-archive
@@ -16,85 +16,104 @@ fi
 
 # Checking vesta user
 if [ ! -e "$VESTA/data/users/$user" ]; then
-    exit 1
+    echo "Error: vesta user $user doesn't exist"
+    exit 3
 fi
 
 # Checking user homedir
 homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z $homedir ]; then
-    exit 1
+    echo "Error: user home directory doesn't exist"
+    exit 12
 fi
 
 # Checking source dir
 if [ ! -e "$src_file" ]; then
-    exit 1
+    echo "Error: source file $src_file doesn't exist"
+    exit 3
 fi
 
 # Checking source path
 rpath=$(readlink -f "$src_file")
 if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-    exit 1
+    echo "Error: invalid source path $src_file"
+    exit 2
 fi
 
 # Checking destination path
 rpath=$(readlink -f "$dst_dir")
 if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-    exit 1
+    echo "Error: invalid destination path $dst_dir"
+    exit 2
 fi
 
 # Extracting gziped archive
 if [ ! -z "$(echo $src_file |egrep -i  '.tgz|.tar.gz')" ]; then
     x='yes'
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user tar -xzf $src_file -C $dst_dir >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user tar -xzf "$src_file" -C "$dst_dir" >/dev/null 2>&1
     rc=$?
 fi
 
 # Extracting bziped archive
 if [ ! -z "$(echo $src_file |egrep -i  '.tbz|.tar.bz')" ]; then
     x='yes'
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user tar -xjf $src_file -C $dst_dir >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user tar -xjf "$src_file" -C "$dst_dir" >/dev/null 2>&1
     rc=$?
 fi
 
 # Extracting gziped file
 if [ ! -z "$(echo $src_file |grep -i  '.gz')" ] && [ -z "$x" ]; then
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user mv $src_file $dst_dir >/dev/null 2>&1
-    sudo -u $user gzip -d $dst_dir/$(basename $src_file) >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user mv "$src_file" "$dst_dir" >/dev/null 2>&1
+    sudo -u $user gzip -d "$dst_dir/$(basename $src_file)" >/dev/null 2>&1
     rc=$?
 fi
 
 # Extracting bziped file
 if [ ! -z "$(echo $src_file |grep -i  '.bz')" ] && [ -z "$x" ]; then
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user mv $src_file $dst_dir >/dev/null 2>&1
-    sudo -u $user bzip2 -d $dst_dir/$(basename $src_file) >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user mv "$src_file" "$dst_dir"# >/dev/null 2>&1
+    sudo -u $user bzip2 -d "$dst_dir/$(basename $src_file)" >/dev/null 2>&1
     rc=$?
 fi
 
 # Extracting ziped archive
 if [ ! -z "$(echo $src_file |grep -i  '.zip')" ]; then
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user unzip $src_file -d $dst_dir >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user unzip "$src_file" -d "$dst_dir" >/dev/null 2>&1
+    rc=$?
+fi
+
+# Extracting ziped archive
+if [ ! -z "$(echo $src_file |grep -i  '.7z')" ]; then
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user mv "$src_file" "$dst_dir" >/dev/null 2>&1
+    sudo -u $user p7zip -d "$src_file" >/dev/null 2>&1
     rc=$?
 fi
 
 # Extracting tared archive
 if [ ! -z "$(echo $src_file |grep -i '.tar')" ] && [ -z "$x" ]; then
     x='yes'
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user tar -xf $src_file -C $dst_dir >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user tar -xf "$src_file" -C "$dst_dir" >/dev/null 2>&1
     rc=$?
 fi
 
 # Extracting rared archive
 if [ ! -z "$(echo $src_file |grep -i  '.rar')" ]; then
-    sudo -u $user mkdir -p $dst_dir >/dev/null 2>&1
-    sudo -u $user unrar $src_file  $dst_dir >/dev/null 2>&1
+    sudo -u $user mkdir -p "$dst_dir" >/dev/null 2>&1
+    sudo -u $user unrar "$src_file"  "$dst_dir" >/dev/null 2>&1
     rc=$?
 fi
 
+# Checking result
+if [ $rc -ne 0 ]; then
+    echo "Error: $src_file was not extracted"
+    exit 3
+fi
+
 # Exiting
-exit $rc
+exit
diff --git a/bin/v-list-fs-directory b/bin/v-list-fs-directory
--- a/bin/v-list-fs-directory
+++ b/bin/v-list-fs-directory
@@ -15,20 +15,23 @@ fi
 
 # Checking vesta user
 if [ ! -e "$VESTA/data/users/$user" ]; then
-    exit 1
+    echo "Error: vesta user $user doesn't exist"
+    exit 3
 fi
 
 # Checking user homedir
 homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z $homedir ]; then
-    exit 1
+    echo "Error: user home directory doesn't exist"
+    exit 12
 fi
 
 # Checking path
 if [ ! -z "$path" ]; then
     rpath=$(readlink -f "$path")
     if [ -z "$(echo $rpath |grep $homedir)" ]; then
-        exit 1
+    echo "Error: invalid path $dst_dir"
+        exit 2
     fi
 else
     path=$homedir
diff --git a/bin/v-move-fs-file b/bin/v-move-fs-file
--- a/bin/v-move-fs-file
+++ b/bin/v-move-fs-file
@@ -17,34 +17,43 @@ fi
 
 # Checking vesta user
 if [ ! -e "$VESTA/data/users/$user" ]; then
-    exit 1
+    echo "Error: vesta user $user doesn't exist"
+    exit 3
 fi
 
 # Checking user homedir
 homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z $homedir ]; then
-    exit 1
+    echo "Error: user home directory doesn't exist"
+    exit 12
 fi
 
 # Checking source file
 if [ ! -f "$src_file" ]; then
-    exit 1
+    echo "Error: source file $src_file doesn't exist"
+    exit 3
 fi
 
 # Checking source path
 rpath=$(readlink -f "$src_file")
 if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-    exit 1
+    echo "Error: invalid source path $src_file"
+    exit 2
 fi
 
 # Checking destination path
 rpath=$(readlink -f "$dst_file")
 if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-    exit 1
+    echo "Error: invalid destination path $dst_file"
+    exit 2
 fi
 
-# Copying file
-sudo -u $user mv $src_file $dst_file >/dev/null 2>&1
+# Moving file
+sudo -u $user mv "$src_file" "$dst_file" >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: file $src_file was not moved"
+    exit 3
+fi
 
 # Exiting
-exit $?
+exit
diff --git a/bin/v-open-fs-file b/bin/v-open-fs-file
--- a/bin/v-open-fs-file
+++ b/bin/v-open-fs-file
@@ -5,35 +5,42 @@
 # The function opens/reads files on the file system
 
 user=$1
-path=$2
+src_file=$2
 
 # Checking arguments
-if [ -z "$path" ]; then
-    echo "Usage: USER PATH"
+if [ -z "$src_file" ]; then
+    echo "Usage: USER FILE"
     exit 1
 fi
 
 # Checking vesta user
 if [ ! -e "$VESTA/data/users/$user" ]; then
-    exit 1
+    echo "Error: vesta user $user doesn't exist"
+    exit 3
 fi
 
 # Checking user homedir
 homedir=$(grep "^$user:" /etc/passwd | cut -f 6 -d :)
 if [ -z $homedir ]; then
-    exit 1
+    echo "Error: user home directory doesn't exist"
+    exit 12
 fi
 
 # Checking path
-if [ ! -z "$path" ]; then
-    rpath=$(readlink -f "$path")
+if [ ! -z "$src_file" ]; then
+    rpath=$(readlink -f "$src_file")
     if [ -z "$(echo $rpath |egrep "^/tmp|^$homedir")" ]; then
-        exit 1
+        echo "Error: invalid source path $src_file"
+        exit 2
     fi
 fi
 
 # Reading file
-sudo -u $user cat "$path"
+sudo -u $user cat "$src_file" 2>/dev/null
+if [ $? -ne 0 ]; then
+    echo "Error: file $src_file was not opened"
+    exit 3
+fi
 
 # Exiting
-exit $?
+exit
