Backend Port: Alignment to main version on GitHub

diff --git a/bin/v-change-sys-port b/bin/v-change-sys-port
--- a/bin/v-change-sys-port
+++ b/bin/v-change-sys-port
@@ -12,7 +12,7 @@
 
 # Argument definition
 PORT=$1
-NGINX_CONFIG="$HESTIA/nginx/conf/nginx.conf"
+NGINX_CONFIG="$HESTIA/nginx/conf/nginx.conf"									
 
 # Includes
 # shellcheck source=/etc/hestiacp/hestia.conf
@@ -24,20 +24,20 @@ source_conf "$HESTIA/conf/hestia.conf"
 
 # Functions
 is_port_valid() {
-    # Check if PORT is numeric
-    if [[ ! "$PORT" =~ ^[0-9]+$ ]]; then
-        echo "Port should contains a numeric value only!"
-        log_event "$E_INVALID" "$ARGUMENTS"
-        exit "$E_INVALID"
-    fi
+	# Check if PORT is numeric
+	if [[ ! "$PORT" =~ ^[0-9]+$ ]]; then
+		echo "Port should contains a numeric value only!"
+		log_event "$E_INVALID" "$ARGUMENTS"
+		exit "$E_INVALID"
+	fi
 
-    # Check if PORT is already used
-    BUSY_PORT=$(lsof -i:"$PORT")
-    if [ -n  "$BUSY_PORT" ] && [ "$PORT" != "$BACKEND_PORT" ]; then
-        echo "Port is already used by Hestia, please set anotherone!"
-        log_event "$E_INUSE" "$ARGUMENTS"
-        exit "$E_INUSE"
-    fi
+	# Check if PORT is already used
+	BUSY_PORT=$(lsof -i:"$PORT")
+	if [ -n "$BUSY_PORT" ] && [ "$PORT" != "$BACKEND_PORT" ]; then
+		echo "Port is already used by Hestia, please set anotherone!"
+		log_event "$E_INUSE" "$ARGUMENTS"
+		exit "$E_INUSE"
+	fi
 }
 
 #----------------------------------------------------------#
@@ -60,37 +60,37 @@ ORIGINAL_PORT=$(cat ${NGINX_CONFIG} | grep -m 1 "listen" | sed 's/[^0-9]*//g')
 
 # Check if port is different to nginx.conf
 if [ "$ORIGINAL_PORT" = "$PORT" ]; then
-    # Nothing to do, exit
-    exit
+	# Nothing to do, exit
+	exit
 else
-    # Set new port in config via v-change-sys-config-value
-    $HESTIA/bin/v-change-sys-config-value "BACKEND_PORT" "$PORT"
-    # Replace port in config files.
-	sed -i "s/\(listen[ \t]*.*[: \t]\)[0-9][0-9]*\([^0-9]*ssl\;$\)/\1$PORT\2/" $HESTIA/nginx/conf/nginx.conf
-    if [ -d /etc/roundcube/ ]; then
-        sed -i "/password_hestia_port/c\$rcmail_config['password_hestia_port'] = '$PORT';" /etc/roundcube/plugins/password/config.inc.php
-    fi
-    if [ -d /etc/rainloop/ ]; then
-        sed -i "/hestia_port/c\hestia_port = $PORT" /etc/rainloop/data/_data_/_default_/configs/plugin-hestia-change-password.ini
-    fi
-    
-    if [ -f "$HESTIA/data/firewall/rules.conf" ]; then
-        sed -i "/COMMENT='HESTIA'/c\RULE='2' ACTION='ACCEPT' PROTOCOL='TCP' PORT='$PORT' IP='0.0.0.0/0' COMMENT='HESTIA' SUSPENDED='no' TIME='07:40:16' DATE='2014-05-25'" $HESTIA/data/firewall/rules.conf
-    fi
-    
-    if [ -f $HESTIA/data/firewall/chains.conf ]; then
-        sed -i "/CHAIN='HESTIA'/c\CHAIN='HESTIA' PORT='$PORT' PROTOCOL='TCP'" $HESTIA/data/firewall/chains.conf
-    fi
-     
-    # Restart services
-    if [ -n "$FIREWALL_SYSTEM" ] && [ "$FIREWALL_SYSTEM" != no ]; then
-        $HESTIA/bin/v-restart-service iptables
-    fi
+	# Set new port in config via v-change-sys-config-value
+	$BIN/v-change-sys-config-value "BACKEND_PORT" "$PORT"
+	# Replace port in config files.
+	sed -i "s/\(listen[ \t]*.*[: \t]\)[0-9][0-9]*\([^0-9]*ssl\;$\)/\1$PORT\2/" ${NGINX_CONFIG}
+	if [ -d /etc/roundcube/ ]; then
+		sed -i "/password_hestia_port/c\$rcmail_config['password_hestia_port'] = '$PORT';" /etc/roundcube/plugins/password/config.inc.php
+	fi
+	if [ -d /etc/rainloop/ ]; then
+		sed -i "/hestia_port/c\hestia_port = $PORT" /etc/rainloop/data/_data_/_default_/configs/plugin-hestia-change-password.ini
+	fi
 
-    # Check if Hestia is running
-    if [[ $(ps -eaf | grep -i hestia |sed '/^$/d' | wc -l) -gt 1 ]]; then
-        $HESTIA/bin/v-restart-service hestia
-    fi  
+	if [ -f "$HESTIA/data/firewall/rules.conf" ]; then
+		sed -i "/COMMENT='HESTIA'/c\RULE='2' ACTION='ACCEPT' PROTOCOL='TCP' PORT='$PORT' IP='0.0.0.0/0' COMMENT='HESTIA' SUSPENDED='no' TIME='07:40:16' DATE='2014-05-25'" $HESTIA/data/firewall/rules.conf
+	fi
+
+	if [ -f $HESTIA/data/firewall/chains.conf ]; then
+		sed -i "/CHAIN='HESTIA'/c\CHAIN='HESTIA' PORT='$PORT' PROTOCOL='TCP'" $HESTIA/data/firewall/chains.conf
+	fi
+
+	# Restart services
+	if [ -n "$FIREWALL_SYSTEM" ] && [ "$FIREWALL_SYSTEM" != no ]; then
+		$BIN/v-restart-service iptables
+	fi
+
+	# Check if Hestia is running
+	if [[ $(ps -eaf | grep -i hestia | sed '/^$/d' | wc -l) -gt 1 ]]; then
+		$BIN/v-restart-service hestia
+	fi
 fi
 
 #----------------------------------------------------------#
