Add support for Yescrypt  for user login

diff --git a/bin/v-check-user-password b/bin/v-check-user-password
--- a/bin/v-check-user-password
+++ b/bin/v-check-user-password
@@ -35,7 +35,7 @@ check_args '2' "$#" 'USER PASSWORD'
 is_format_valid 'user'
 
 # Checking user
-if [ ! -d "$HESTIA/data/users/$user" ] && [ "$user" != 'root' ]; then
+if [ ! -d "$HESTIA/data/users/$user" ]; then
     echo "Error: password missmatch"
     echo "$date $time $user $ip failed to login" >> $HESTIA/log/auth.log
     exit 9
@@ -63,8 +63,7 @@ then
     salt=$(echo "$shadow" |cut -f 3 -d \$)
     method=$(echo "$shadow" |cut -f 2 -d \$)
     if [ "$method" = "y" ]; then
-        echo "Unsuported hash method";
-        exit 1;   
+        method="yescrypt" 
     elif [ "$method" -eq '1' ]; then
         method='md5'
     elif [ "$method" -eq '6' ]; then
@@ -85,13 +84,22 @@ if [ -z "$salt" ]; then
     exit 9
 fi
 
-# Generating hash
-set -o noglob
-hash=$($BIN/v-generate-password-hash "$method" "$salt" <<< "$password")
-if [[ -z "$hash" ]]; then
-    echo "Error: password missmatch"
-    echo "$date $time $user $ip failed to login" >> $HESTIA/log/auth.log
-    exit 9
+if [ "$method" = "yescrypt" ]; then
+    hash=$(mkpasswd "$password" "$shadow")
+    if [ $? -ne 0 ]; then 
+        echo "Error: password missmatch"
+        echo "$date $time $user $ip failed to login" >> $HESTIA/log/auth.log
+        exit 9
+    fi
+else
+    # Generating hash
+    set -o noglob
+    hash=$($BIN/v-generate-password-hash "$method" "$salt" <<< "$password")
+    if [[ -z "$hash" ]]; then
+        echo "Error: password missmatch"
+        echo "$date $time $user $ip failed to login" >> $HESTIA/log/auth.log
+        exit 9
+    fi
 fi
 
 # Checking hash
@@ -106,6 +114,7 @@ fi
 #                       Hestia                             #
 #----------------------------------------------------------#
 
+echo $hash;
 # Logging
 echo "$date $time $user $ip successfully logged in" >> $HESTIA/log/auth.log
 
