Fix an bug where $RELEASE_BRANCH is not hosted at hestia github
Download of api will fail and api will not work. No error is provided

diff --git a/bin/v-change-sys-api b/bin/v-change-sys-api
--- a/bin/v-change-sys-api
+++ b/bin/v-change-sys-api
@@ -37,13 +37,15 @@ check_hestia_demo_mode
 if [ "$status" = "enable" ]; then
     if [ ! -f "$HESTIA/web/api/index.php" ]; then
         wget -q https://raw.githubusercontent.com/hestiacp/hestiacp/$RELEASE_BRANCH/web/api/index.php -O $HESTIA/web/api/index.php
-        check_api_download=$(cat $HESTIA/web/api/index.php)
-        if [ -z "$HESTIA/web/api/index.php" ]; then
-            # Throw error message to user
-            echo "ERROR: API installation failed."
-            # Remove empty file created by wget output
-            rm -f "$HESTIA/web/api/index.php"
-            exit 1
+        if [ ! -s $HESTIA/web/api/index.php ]; then
+            wget -q https://raw.githubusercontent.com/hestiacp/hestiacp/release/web/api/index.php -O $HESTIA/web/api/index.php    
+            if [ ! -s $HESTIA/web/api/index.php ]; then
+                # Throw error message to user
+                echo "ERROR: API installation failed."
+                # Remove empty file created by wget output
+                rm -f "$HESTIA/web/api/index.php"
+                exit 1
+            fi
         fi
     else
         sed -i 's|die("Error: Disabled");|//die("Error: Disabled");|g' $HESTIA/web/api/index.php
