prettier code correction after last commit

diff --git a/bin/v-check-user-password b/bin/v-check-user-password
--- a/bin/v-check-user-password
+++ b/bin/v-check-user-password
@@ -85,14 +85,14 @@ if [ -z "$salt" ]; then
 fi
 
 if [ "$method" = "yescrypt" ]; then
-        hash=$(mkpasswd "$password" "$shadow")
-        if [ $? -ne 0 ]; then
-                echo "Error: password missmatch"
-                if [ -z "$return_hash" ]; then
-                        echo "$date $time $user $ip46 failed to login" >> $HESTIA/log/auth.log
-                fi
-                exit 9
-        fi
+	hash=$(mkpasswd "$password" "$shadow")
+	if [ $? -ne 0 ]; then
+		echo "Error: password missmatch"
+		if [ -z "$return_hash" ]; then
+			echo "$date $time $user $ip46 failed to login" >> $HESTIA/log/auth.log
+		fi
+		exit 9
+	fi
 else
 	# Generating hash
 	set -o noglob
