IPV6: Manual merge after #3605 and update from upstream

diff --git a/bin/v-delete-sys-ip b/bin/v-delete-sys-ip
--- a/bin/v-delete-sys-ip
+++ b/bin/v-delete-sys-ip
@@ -1,30 +1,30 @@
 #!/bin/bash
-# info: delete system ip
+# info: delete system IP
 #       both kind of IP addresses, ipv4 and ipv6 are allowed
 # options: IP
 #
-# example: v-delete-sys-ip 212.42.76.210
+# example: v-delete-sys-ip 203.0.113.1
 # example: v-delete-sys-ip 1234:5678:abcd:ef90::1
 #
-# This function for deleting a system ip. It does not allow to delete first ip
-# on interface and do not allow to delete ip which is used by a web domain.
+# This function for deleting a system IP. It does not allow to delete first IP
+# on interface and do not allow to delete IP which is used by a web domain.
 
 #----------------------------------------------------------#
 #                Variables & Functions                     #
 #----------------------------------------------------------#
 
 # Argument definition
-ip46=${1%/*}	# clean ip address without cidr/prefix_length
+ip46=${1%/*} # clean ip address without cidr/prefix_length
 
 # Includes
 # shellcheck source=/etc/hestiacp/hestia.conf
 source /etc/hestiacp/hestia.conf
 # shellcheck source=/usr/local/hestia/func/main.sh
-source $HESTIA/func/main.sh
+source ${HESTIA}/func/main.sh
 # shellcheck source=/usr/local/hestia/func/ip.sh
-source $HESTIA/func/ip.sh
+source ${HESTIA}/func/ip.sh
 # shellcheck source=/usr/local/hestia/func/domain.sh
-source $HESTIA/func/domain.sh
+source ${HESTIA}/func/domain.sh
 # load config file
 source_conf "$HESTIA/conf/hestia.conf"
 
@@ -33,7 +33,7 @@ source_conf "$HESTIA/conf/hestia.conf"
 #----------------------------------------------------------#
 
 check_args '1' "$#" 'IP'
-ip_format="$(get_ip_format ${ip46})"	#	ip verification and format identification
+ip_format="$(get_ip_format ${ip46})" #	ip verification and format identification
 retval=$?
 check_ip_par=""
 add_cap_string_ipv6=""
@@ -64,8 +64,8 @@ check_hestia_demo_mode
 #                       Action                             #
 #----------------------------------------------------------#
 
-# Import ip variables
-source $HESTIA/data/ips/${ip46}
+# Import IP variables
+source ${HESTIA}/data/ips/${ip46}
 if [ $ip_format -eq 6 ]; then
 	prefix_length=${NETMASK}
 	is_format_valid 'prefix_length'
@@ -76,27 +76,28 @@ else
 	cidr_prefixlen=$(convert_netmask "$netmask")
 fi
 
-host_ip_check=$(hostname -i | sed -ne "/$ip46/p") # check, if IP address is main (listed in /etc/hosts)
+host_ip_check=$(hostname -i | sed -ne "/$ip46/p")                                                # check, if IP address is primary (listed in /etc/hosts)
 interface=$($BIN/v-list-network plain | sed -ne "/$ip46/s/$ip46[ \t]*\/[0-9]*[ \t]*\(.*\)/\1/p") # interface for IP address
-number_of_ips=$(/sbin/ip${check_ip_par} addr | grep -c global) # number of global system IP addresses
+number_of_ips=$(/sbin/ip${check_ip_par} addr | grep -c global)                                   # number of global system IP addresses
 
-if [[ ( -n "$host_ip_check" && -n "$interface" ) || ( $number_of_ips -eq 1 ) ]]; then
-	echo "Error: can't delete main IP address"
+if [[ (-n "$host_ip_check" && -n "$interface") || ($number_of_ips -eq 1) ]]; then
+	echo "Error: can't delete primary IP address"
 	log_event "$E_FORBIDEN" "$ARGUMENTS"
 	exit "$E_FORBIDEN"
 fi
 
-# Deleting system ip
+# Deleting system IP
 if [ -n "$interface" ]; then
-	/sbin/ip addr del "$ip46$cidr_prefixlen" dev ${INTERFACE%:*}
+	ip addr del "$ip46$cidr_prefixlen" dev ${INTERFACE%:*}
 	if [ "$?" -ne 0 ]; then
-		echo "Error: can't delete system ip"
+		echo "Error: can't delete system IP address"
 		log_event "$E_FORBIDEN" "$ARGUMENTS"
-		exit $E_FORBIDEN
+		exit "$E_FORBIDEN"
 	fi
 fi
 
 # Deleting startup conf on RHEL/CentOS/Fedora
+# Need RHEL experts to fix me
 if [ -e "/etc/sysconfig/network-scripts/ifcfg-$interface" ]; then
 	rm -f /etc/sysconfig/network-scripts/ifcfg-$interface
 fi
@@ -110,10 +111,10 @@ if [ -f "/etc/netplan/60-hestia.yaml" ]; then
 elif [ -e "/etc/network/interfaces" ]; then
 	if [ $ip_format -eq 6 ]; then
 		filter_ip="${ip46}${cidr_prefixlen}"
-		lines_after=0	# ipv6 is defined using prefix length in one line
+		lines_after=0 # ipv6 is defined using prefix length in one line
 	else
 		filter_ip="${ip46}"
-		lines_after=1	# ipv4 is defined using netmask in a separate line
+		lines_after=1 # ipv4 is defined using netmask in a separate line
 	fi
 	ip_str=$(grep -n $filter_ip$ /etc/network/interfaces | cut -f1 -d:)
 	if [ -n "$ip_str" ]; then
@@ -123,38 +124,38 @@ elif [ -e "/etc/network/interfaces" ]; then
 	fi
 fi
 
-# Deleting hestia ip
-rm -f $HESTIA/data/ips/${ip46}
+# Deleting Hestia IP
+rm -f ${HESTIA}/data/ips/${ip46}
 
 # Deleting web config
 if [ -n "$WEB_SYSTEM" ]; then
-	rm -f /etc/$WEB_SYSTEM/conf.d/${ip46}.conf
+	rm -f /etc/${WEB_SYSTEM}/conf.d/${ip46}.conf
 fi
 
 # Deleting proxy config
 if [ -n "$PROXY_SYSTEM" ]; then
-	rm -f /etc/$PROXY_SYSTEM/conf.d/${ip46}.conf
+	rm -f /etc/${PROXY_SYSTEM}/conf.d/${ip46}.conf
 
 	# mod_extract_forwarded
 	fw_conf="/etc/$WEB_SYSTEM/conf.d/mod_extract_forwarded.conf"
 	if [ -e "$fw_conf" ]; then
-		ips=$(grep 'MEFaccept 127.0.0.1' $fw_conf)
-		new_ips=$(echo "$ips" | sed "s/$ip46//")
-		sed -i "s/$ips/$new_ips/g" $fw_conf
+		ips="$(grep 'MEFaccept 127.0.0.1' ${fw_conf})"
+		new_ips="$(echo "$ips" | sed "s/$ip46//")"
+		sed -i "s/$ips/$new_ips/g" ${fw_conf}
 	fi
 
 	# mod_rpaf
 	rpaf_conf="/etc/$WEB_SYSTEM/mods-enabled/rpaf.conf"
 	if [ -e "$rpaf_conf" ]; then
-		ips=$(grep RPAFproxy_ips "$rpaf_conf")
-		new_ips=$(echo "$ips" | sed "s/ $ip46//")
-		sed -i "s/$ips/$new_ips/g" "$rpaf_conf"
+		ips="$(grep RPAFproxy_ips ${rpaf_conf})"
+		new_ips="$(echo "$ips" | sed "s/ $ip46//")"
+		sed -i "s/$ips/$new_ips/g" ${rpaf_conf}
 
 		# Remove RPAFproxy_ips line when ip list is empty
-		[ "$(grep RPAFproxy_ips $rpaf_conf | sed 's/^[[:space:]]*//g')" = "RPAFproxy_ips" ] && sed -i "/RPAFproxy_ips/d" $rpaf_conf
+		[ "$(grep RPAFproxy_ips ${rpaf_conf} | sed 's/^[[:space:]]*//g')" = "RPAFproxy_ips" ] && sed -i "/RPAFproxy_ips/d" ${rpaf_conf}
 	fi
 
-	#mod_remoteip
+	# mod_remoteip
 	remoteip_conf="/etc/$WEB_SYSTEM/mods-enabled/remoteip.conf"
 	if [ -e "$remoteip_conf" ]; then
 		sed -i "/RemoteIPInternalProxy $ip46\$/d" "$remoteip_conf"
@@ -172,7 +173,7 @@ fi
 
 if [ "$OWNER" = 'admin' ]; then
 	if [ "$STATUS" = 'shared' ]; then
-		for hestia_user in $($BIN/v-list-sys-users plain); do
+		for hestia_user in $(${BIN}/v-list-sys-users plain); do
 			decrease_user_value "$hestia_user" '$IP'$add_cap_string_ipv6'_AVAIL'
 		done
 	else
@@ -183,22 +184,22 @@ else
 fi
 
 # Restarting web server
-$BIN/v-restart-web
+${BIN}/v-restart-web
 check_result $? "Web restart failed" > /dev/null
 
 # Restarting proxy server
 if [ -n "$PROXY_SYSTEM" ]; then
-	$BIN/v-restart-proxy
+	${BIN}/v-restart-proxy
 	check_result $? "Proxy restart failed" > /dev/null
 fi
 
 # Restarting firewall
 if [ -n "$FIREWALL_SYSTEM" ]; then
-	$BIN/v-update-firewall
+	${BIN}/v-update-firewall
 fi
 
 # Logging
-$BIN/v-log-action "system" "Info" "System" "IP address deleted (IP: $ip46)."
+${BIN}/v-log-action "system" "Info" "System" "IP address deleted (IP: $ip46)."
 log_event "$OK" "$ARGUMENTS"
 
 exit
