fix(ipv6): normalize and validate prefix length before deleting IP

diff --git a/bin/v-delete-sys-ip b/bin/v-delete-sys-ip
--- a/bin/v-delete-sys-ip
+++ b/bin/v-delete-sys-ip
@@ -66,35 +66,49 @@ check_hestia_demo_mode
 
 # Import IP variables
 source ${HESTIA}/data/ips/${ip46}
+
+# Normalizar y validar NETMASK/prefix
 if [ $ip_format -eq 6 ]; then
-	prefix_length=${NETMASK}
-	is_format_valid 'prefix_length'
-	cidr_prefixlen=${prefix_length}
+    prefix_length=${NETMASK#/}  # quita la barra si existe
+    if ! [[ "$prefix_length" =~ ^[0-9]{1,3}$ ]]; then
+        echo "Error: invalid prefix_length format: $prefix_length"
+        exit 1
+    fi
+    if ((prefix_length < 0 || prefix_length > 128)); then
+        echo "Error: prefix_length out of range: $prefix_length"
+        exit 1
+    fi
+    cidr_prefixlen="/$prefix_length"
 else
-	netmask=${NETMASK}
-	is_format_valid 'netmask'
-	cidr_prefixlen=$(convert_netmask "$netmask")
+    netmask=${NETMASK}
+    is_format_valid 'netmask'
+    cidr_prefixlen="/$(convert_netmask "$netmask")"
 fi
 
 host_ip_check=$(hostname -i | sed -ne "/$ip46/p") # check, if IP address is primary (listed in /etc/hosts)
-# shellcheck disable=SC1087
 interface=$($BIN/v-list-network plain | sed -ne "/$ip46/s/$ip46[ \t]*\/[0-9]*[ \t]*\(.*\)/\1/p") # interface for IP address
-number_of_ips=$(/sbin/ip${check_ip_par} addr | grep -c global)                                   # number of global system IP addresses
+number_of_ips=$(/sbin/ip${check_ip_par} addr | grep -c global) # number of global system IP addresses
 
 if [[ (-n "$host_ip_check" && -n "$interface") || ($number_of_ips -eq 1) ]]; then
-	echo "Error: can't delete primary IP address"
-	log_event "$E_FORBIDEN" "$ARGUMENTS"
-	exit "$E_FORBIDEN"
+    echo "Error: can't delete primary IP address"
+    log_event "$E_FORBIDEN" "$ARGUMENTS"
+    exit "$E_FORBIDEN"
 fi
+
+# Opcional: debug
+# echo "ip46: $ip46"
+# echo "cidr_prefixlen: $cidr_prefixlen"
+# echo "comando final: ip addr del $ip46$cidr_prefixlen dev ${INTERFACE%:*}"
 
 # Deleting system IP
 if [ -n "$interface" ]; then
-	ip addr del "$ip46$cidr_prefixlen" dev ${INTERFACE%:*}
-	if [ "$?" -ne 0 ]; then
-		echo "Error: can't delete system IP address"
-		log_event "$E_FORBIDEN" "$ARGUMENTS"
-		exit "$E_FORBIDEN"
-	fi
+    echo "Deleting IP: $ip46$cidr_prefixlen on interface ${INTERFACE%:*}"
+    ip addr del "$ip46$cidr_prefixlen" dev ${INTERFACE%:*}
+    if [ "$?" -ne 0 ]; then
+        echo "Error: can't delete system IP address"
+        log_event "$E_FORBIDEN" "$ARGUMENTS"
+        exit "$E_FORBIDEN"
+    fi
 fi
 
 # Deleting startup conf on Debian/Ubuntu
