Minor updates

diff --git a/bin/v-delete-sys-ip b/bin/v-delete-sys-ip
--- a/bin/v-delete-sys-ip
+++ b/bin/v-delete-sys-ip
@@ -1,11 +1,11 @@
 #!/bin/bash
-# info: delete system ip
+# info: delete system IP
 # options: IP
 #
-# example: v-delete-sys-ip 212.42.76.210
+# example: v-delete-sys-ip 203.0.113.1
 #
-# This function for deleting a system ip. It does not allow to delete first ip
-# on interface and do not allow to delete ip which is used by a web domain.
+# This function for deleting a system IP. It does not allow to delete first IP
+# on interface and do not allow to delete IP which is used by a web domain.
 
 #----------------------------------------------------------#
 #                Variables & Functions                     #
@@ -44,29 +44,33 @@ check_hestia_demo_mode
 #----------------------------------------------------------#
 
 # Import IP variables
-source $HESTIA/data/ips/$ip
+source "$HESTIA/data/ips/$ip"
 cidr="$(convert_netmask "$NETMASK")"
-main_ip="$(hostname -i)"
 
-# Checking main ip on the interface
-interface=$(ip addr | grep "$ip/$cidr" | awk '{print $NF}')
-if [ -n "$interface" ] && [ "$ip" = "$main_ip" ]; then
-	echo "Error: can't delete main IP address"
+# Get primary IP
+default_nic="$(ip -d -j route show | jq -r '.[] | if .dst == "default" then .dev else empty end')"
+primary_ipv4="$(ip -4 -d -j addr show "$default_nic" | jq -r '.[].addr_info[] | if .scope == "global" then .local else empty end' | head -n1)"
+
+# Checking primary IP on the interface
+interface="$(ip -d -j addr show | jq --arg IP "$ip" -r '.[] | if .addr_info[].local == $IP then .ifname else empty end')"
+if [ -n "$interface" ] && [ "$ip" = "$primary_ipv4" ]; then
+	echo "Error: can't delete primary IP address"
 	log_event "$E_FORBIDEN" "$ARGUMENTS"
 	exit "$E_FORBIDEN"
 fi
 
 # Deleting system IP
 if [ -n "$interface" ]; then
-	ip addr del "$ip/$cidr" dev "$INTERFACE" 2> /dev/null
-	if [ "$?" -ne 0 ]; then
-		echo "Error: can't delete system ip"
+	ip addr del "$ip/$cidr" dev "$interface" 2> /dev/null
+	if [ "$?" -ne "0" ]; then
+		echo "Error: can't delete system IP address"
 		log_event "$E_FORBIDEN" "$ARGUMENTS"
-		exit $E_FORBIDEN
+		exit "$E_FORBIDEN"
 	fi
 fi
 
 # Deleting startup conf on RHEL/CentOS/Fedora
+# Need RHEL experts to fix me
 if [ -e "/etc/sysconfig/network-scripts/ifcfg-$interface" ]; then
 	rm -f /etc/sysconfig/network-scripts/ifcfg-$interface
 fi
@@ -78,10 +82,10 @@ if [ -f "/etc/netplan/60-hestia.yaml" ]; then
 		rm /etc/netplan/60-hestia.yaml
 	fi
 elif [ -e "/etc/network/interfaces" ]; then
-	ip_str=$(grep -n $ip$ /etc/network/interfaces | cut -f1 -d:)
+	ip_str="$(grep -n "$ip$" /etc/network/interfaces | cut -f1 -d:)"
 	if [ -n "$ip_str" ]; then
-		first_str=$((ip_str - 3))
-		last_str=$((ip_str + 1))
+		first_str="$((ip_str - 3))"
+		last_str="$((ip_str + 1))"
 		sed -i "$first_str,$last_str d" /etc/network/interfaces
 	fi
 fi
