Notifiy user when suspended (#2345)
* Notifiy user when suspended

Add error message when user tries to login

* Force users to use hostname instead any domain

Possible method for gaining access via clientdomain.com and changing DNS

diff --git a/bin/v-get-user-salt b/bin/v-get-user-salt
--- a/bin/v-get-user-salt
+++ b/bin/v-get-user-salt
@@ -93,6 +93,10 @@ then
         echo "$date $time $user $ip failed to login" >> $HESTIA/log/auth.log
         exit 9
     fi
+elif [[ "$shadow" =~ ! ]]; then 
+    echo "Error: Account has been suspended"
+    echo "$date $time $user $ip has been suspended" >> $HESTIA/log/auth.log
+    exit 5
 else
     salt=${shadow:0:2}
     method='des'
