Update v-import-cpanel Fix 500 Error from php version
Some users reported 500 Error after migration so I edited the script to check the installed versions on hestia and set the php version based on the backup file if it available

diff --git a/bin/v-import-cpanel b/bin/v-import-cpanel
--- a/bin/v-import-cpanel
+++ b/bin/v-import-cpanel
@@ -251,6 +251,27 @@ rsync -av --exclude-from='exclude_path' homedir/public_html/ /home/$new_user/web
 chown $new_user:$new_user -R /home/$new_user/web/$main_domain1/public_html
 chmod 751 /home/$new_user/web/$main_domain1/public_html
 
+####### Set Domain PHP version
+PHP_VERSION_LINE=$(grep -r "phpversion:" userdata/$main_domain1)
+CPANEL_PHP_VERSION=${PHP_VERSION_LINE#*: }
+CPANEL_PHP_VERSION=$(echo $CPANEL_PHP_VERSION | grep -oP '(?<=php)\d+')
+HESTIA_PHP_VERSION="PHP-${CPANEL_PHP_VERSION:0:1}_${CPANEL_PHP_VERSION:1}"
+
+if /usr/local/hestia/bin/v-list-web-templates-backend | grep -qw "$HESTIA_PHP_VERSION"; then
+    echo "Setting PHP version to $HESTIA_PHP_VERSION for $main_domain1 under user $new_user"
+    /usr/local/hestia/bin/v-change-web-domain-backend-tpl $new_user $main_domain1 $HESTIA_PHP_VERSION
+    if [ $? -ne 0 ]; then
+        echo "Failed to set PHP version for $main_domain1"
+        exit 1
+    else
+        echo "PHP version for $main_domain1 set to $HESTIA_PHP_VERSION"
+    fi
+else
+    echo "PHP version $HESTIA_PHP_VERSION is not installed on HestiaCP."
+    echo "Please install it before trying to set it for a domain."
+    exit 1
+fi
+
 ##################
 # mail
 tput setaf 2
