Few minor changes

diff --git a/bin/v-import-cpanel b/bin/v-import-cpanel
--- a/bin/v-import-cpanel
+++ b/bin/v-import-cpanel
@@ -256,26 +256,32 @@ chmod 751 /home/$new_user/web/$main_domain1/public_html
 ####### Set Domain PHP version
 PHP_VERSION_LINE=$(grep -r "phpversion:" userdata/$main_domain1)
 CPANEL_PHP_VERSION=${PHP_VERSION_LINE#*: }
-CPANEL_PHP_VERSION=$(echo $CPANEL_PHP_VERSION | grep -oP '(?<=php)\d+')
-HESTIA_PHP_VERSION="PHP-${CPANEL_PHP_VERSION:0:1}_${CPANEL_PHP_VERSION:1}"
+if [ -n "$CPANEL_PHP_VERSION" ]; then
+	CPANEL_PHP_VERSION=$(echo $CPANEL_PHP_VERSION | grep -oP '(?<=php)\d+')
+	HESTIA_PHP_VERSION="PHP-${CPANEL_PHP_VERSION:0:1}_${CPANEL_PHP_VERSION:1}"
 
-if $BIN/v-list-web-templates-backend | grep -qw "$HESTIA_PHP_VERSION"; then
-	echo "Setting PHP version to $HESTIA_PHP_VERSION for $main_domain1 under user $new_user"
-	$BIN/v-change-web-domain-backend-tpl $new_user $main_domain1 $HESTIA_PHP_VERSION
-	if [ $? -ne 0 ]; then
-		tput setaf 1
-			echo "ERROR!! Failed to set same PHP version for $main_domain1 setting default, please check this to avoid errors."
-			sleep 3
-		tput sgr0
+	if $BIN/v-list-web-templates-backend | grep -qw "$HESTIA_PHP_VERSION"; then
+		echo "Setting PHP version to $HESTIA_PHP_VERSION for $main_domain1 under user $new_user"
+		$BIN/v-change-web-domain-backend-tpl $new_user $main_domain1 $HESTIA_PHP_VERSION
+		if [ $? -ne 0 ]; then
+			tput setaf 1
+				echo "ERROR!! Failed to set same PHP version for $main_domain1 setting default, please check this to avoid errors."
+			tput sgr0
+		else
+			echo "PHP version for $main_domain1 set to $HESTIA_PHP_VERSION"
+		fi
 	else
-		echo "PHP version for $main_domain1 set to $HESTIA_PHP_VERSION"
+		tput setaf 1
+			echo "PHP version $HESTIA_PHP_VERSION is not installed on HestiaCP."
+			echo "Please install and set it to avoid errors in website."
+			echo "The restoration will continue but the website may not work as expected"
+		tput sgr0
 	fi
 else
 	tput setaf 1
-		echo "PHP version $HESTIA_PHP_VERSION is not installed on HestiaCP."
-		echo "Please install and set it to avoid errors in website."
-		echo "The restoration will continue but the website may not work as expected" 
-		sleep 3
+		echo "Unable to detect PHP version used on old server"
+		echo "Please check you old PHP version and set the PHP version in domain settings"
+		echo "The restoration will continue but the website may not work as expected"
 	tput sgr0
 fi
 
