Update logging in v-scripts

diff --git a/bin/v-log-action b/bin/v-log-action
--- a/bin/v-log-action
+++ b/bin/v-log-action
@@ -2,13 +2,15 @@
 # info: adds action event to user or system log
 # options: LOG_TYPE USER
 
-# Argument definition
-log_type=$1
-event_type=$2
-user=$3
-event_details=${4-$3}
 
-echo $event_details
+# Event Levels:
+# info, warning, error
+
+# Event Categories:
+# user:     web, dns, mail, db, letsencrypt, pwchange, pwreset
+# system:   ip, firewall, service, updates,
+#           users, pwchange, pwreset, impersonation
+
 
 # Includes
 source $HESTIA/func/main.sh
@@ -17,29 +19,44 @@ source $HESTIA/conf/hestia.conf
 #----------------------------------------------------------#
 #                    Verifications                         #
 #----------------------------------------------------------#
+# Argument definition
+user=$1
+event_level=$2
+event_category=$3
+event_details=$4
 
 # Generating timestamp
 time_n_date=$(date +'%T %F')
 time=$(echo "$time_n_date" |cut -f 1 -d \ )
 date=$(echo "$time_n_date" |cut -f 2 -d \ )
 
+# Validate event type input
+if [ "$event_level" != "Info" ] && [ "$event_level" != "Warning" ] && [ "$event_level" != "Error" ]; then 
+    echo "Error: Invalid event type specified."
+    exit 1
+fi
+
 #----------------------------------------------------------#
 #                       Action                             #
 #----------------------------------------------------------#
 
-# Provide context switch for different log types
-if [ "$log_type" = "user" ]; then
-    check_args '4' "$#" 'LOG_TYPE EVENT_TYPE USER MESSAGE'
-    is_object_valid 'user' 'USER' "$user"
-    log_history "'$event_details" '' "$user"
-    exit
+if [ "$user" = "system" ] || [ "$user" = "System" ]; then
+    user="admin"
 fi
 
-if [ "$log_type" = "system" ]; then
-    check_args '3' "$#" 'LOG_TYPE EVENT_TYPE MESSAGE'
-    log_history "$event_details" '' 'admin'
-    exit
+check_args '4' "$#" 'USER TYPE CATEGORY DETAILS'
+is_object_valid 'user' 'USER' "$user"
+
+# Future hooks for login/logout events, currently housed in v-log-user-login and v-log-user-logout
+if [ "$event_category" = "login" ] || [ "$event_category" = "Login" ]; then
+echo "login hook used"
 fi
+
+if [ "$event_category" = "logout" ] || [ "$event_category" = "Logout" ]; then
+echo "logout hook used"
+fi
+
+log_history "$event_details" '' "$user"
 
 #----------------------------------------------------------#
 #                       Hestia                             #
diff --git a/bin/v-start-service b/bin/v-start-service
--- a/bin/v-start-service
+++ b/bin/v-start-service
@@ -44,8 +44,10 @@ for service in $service_list; do
         $BIN/v-update-firewall
     else
         systemctl start $service > /dev/null 2>&1
+        $BIN/v-log-action "system" "Error" "System" "Service started (Name: $service)."
     fi
     check_result $? "ERROR: $service start failed" $E_RESTART
+    check_result $? $BIN/v-log-action "system" "Error" "System" "Service failed to start (Name: $service)."
 done
 
 
