Added file check

diff --git a/bin/v-open-fs-file b/bin/v-open-fs-file
--- a/bin/v-open-fs-file
+++ b/bin/v-open-fs-file
@@ -33,6 +33,11 @@ if [ ! -z "$src_file" ]; then
         echo "Error: invalid source path $src_file"
         exit 2
     fi
+    
+    if [ ! -f "$src_file" ]; then
+        echo "Error: file not found $src_file"
+        exit 2
+    fi
 fi
 
 # Reading file
