Make restart check mandetory

diff --git a/bin/v-restart-web b/bin/v-restart-web
--- a/bin/v-restart-web
+++ b/bin/v-restart-web
@@ -42,6 +42,18 @@ send_email_report() {
 }
 
 #----------------------------------------------------------#
+#                    Verifications                         #
+#----------------------------------------------------------#
+
+is_format_valid 'restart'
+
+if [[ ! $version =~ ^[0-9]\.[0-9]+ ]]; then
+	echo "The specified PHP version format is invalid, it should look like [0-9].[0-9]."
+	echo "Example: 7.0, 7.4, 8.0"
+	exit "$E_INVALID"
+fi
+
+#----------------------------------------------------------#
 #                       Action                             #
 #----------------------------------------------------------#
 
