Update logging in v-scripts

diff --git a/bin/v-start-service b/bin/v-start-service
--- a/bin/v-start-service
+++ b/bin/v-start-service
@@ -43,11 +43,15 @@ for service in $service_list; do
     if [ "$service" = "iptables" ]; then
         $BIN/v-update-firewall
     else
-        systemctl start $service > /dev/null 2>&1
-        $BIN/v-log-action "system" "Error" "System" "Service started (Name: $service)."
+        systemctl start $service
+        result=$?
+        if [ "$result" -ne 0 ]; then
+            $BIN/v-log-action "system" "Error" "System" "Service failed to start (Name: $service)."
+        else
+            $BIN/v-log-action "system" "Info" "System" "Service started (Name: $service)."
+        fi
     fi
     check_result $? "ERROR: $service start failed" $E_RESTART
-    check_result $? $BIN/v-log-action "system" "Error" "System" "Service failed to start (Name: $service)."
 done
 
 
diff --git a/bin/v-stop-service b/bin/v-stop-service
--- a/bin/v-stop-service
+++ b/bin/v-stop-service
@@ -46,11 +46,16 @@ for service in $service_list; do
     if [ "$service" = "iptables" ]; then
         $BIN/v-stop-firewall
     else
-        systemctl stop $service >/dev/null 2>&1
-        $BIN/v-log-action "system" "Info" "System" "Service stopped (Name: $service)."
+        systemctl stop $service
+        result=$?
+        if [ "$result" -ne 0 ]; then
+            $BIN/v-log-action "system" "Error" "System" "Service failed to stop (Name: $service)."
+        else
+            $BIN/v-log-action "system" "Info" "System" "Service stopped (Name: $service)."
+        fi
     fi
     check_result $? "ERROR: $service stop failed" $E_RESTART
-    $BIN/v-log-action "system" "Error" "System" "Service failed to stop (Name: $service)."
+
 done
 
 
