Prettier

diff --git a/bin/v-update-firewall b/bin/v-update-firewall
--- a/bin/v-update-firewall
+++ b/bin/v-update-firewall
@@ -35,9 +35,9 @@ is_system_enabled "$FIREWALL_SYSTEM" 'FIREWALL_SYSTEM'
 # Acquire firewall lock to serialize concurrent firewall state modifications
 # (fail2ban ban/unban, rule changes, etc.)
 if [ -z "${HESTIA_FIREWALL_LOCK_HELD:-}" ]; then
-	exec 9>/run/hestia-firewall.lock
-	flock -w 30 9
-	export HESTIA_FIREWALL_LOCK_HELD=1
+  exec 9> /run/hestia-firewall.lock
+  flock -w 30 9
+  export HESTIA_FIREWALL_LOCK_HELD=1
 fi
 
 #----------------------------------------------------------#
@@ -51,21 +51,21 @@ heal_iptables_links
 rules="$HESTIA/data/firewall/rules.conf"
 
 if [ ! -e "$rules" ]; then
-	exit
+  exit
 fi
 
 # Checking conntrack module avaiabilty
 "$modprobe" nf_conntrack > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-	"$sysctl" net.netfilter.nf_conntrack_max > /dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		conntrack='no'
-	fi
+  "$sysctl" net.netfilter.nf_conntrack_max > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    conntrack='no'
+  fi
 fi
 
 "$modprobe" nf_conntrack_ftp > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-	conntrack_ftp='no'
+  conntrack_ftp='no'
 fi
 
 chains="$HESTIA/data/firewall/chains.conf"
@@ -74,12 +74,12 @@ banlist="$HESTIA/data/firewall/banlist.conf"
 # Detect custom OpenSSH port(s) and update SSH chain
 sshport=$("$BIN/v-list-sys-sshd-port" plain | paste -sd ',' -)
 if [[ "$sshport" =~ ^[0-9]+(,[0-9]+)*$ ]]; then
-	sed -i -E "s/(PORT=')[0-9]+(,[0-9]+)*('.*COMMENT='SSH')/\1${sshport}\3/" "$rules"
-	if [[ -f "$chains" ]]; then
-		sed -i "/CHAIN='SSH'/c\\CHAIN='SSH' PORT='${sshport}' PROTOCOL='TCP'" "$chains"
-	else
-		"$BIN/v-add-firewall-chain" 'SSH' "$sshport" 'TCP'
-	fi
+  sed -i -E "s/(PORT=')[0-9]+(,[0-9]+)*('.*COMMENT='SSH')/\1${sshport}\3/" "$rules"
+  if [[ -f "$chains" ]]; then
+    sed -i "/CHAIN='SSH'/c\\CHAIN='SSH' PORT='${sshport}' PROTOCOL='TCP'" "$chains"
+  else
+    "$BIN/v-add-firewall-chain" 'SSH' "$sshport" 'TCP'
+  fi
 fi
 
 # Load ipset lists before adding Hestia iptables rules
@@ -96,85 +96,85 @@ echo "$iptables -F INPUT" >> "$tmp"
 echo "$iptables -A INPUT -i lo -j ACCEPT" >> "$tmp"
 ips="$(ls $HESTIA/data/ips)"
 for ip in $ips; do
-	echo "$iptables -A INPUT -s $ip -j ACCEPT" >> "$tmp"
+  echo "$iptables -A INPUT -s $ip -j ACCEPT" >> "$tmp"
 done
 
 # Enabling stateful support
 if [ "$conntrack" != 'no' ] || grep --quiet container=lxc /proc/1/environ; then
-	str="$iptables -A INPUT -m state"
-	str="$str --state ESTABLISHED,RELATED -j ACCEPT"
-	echo "$str" >> "$tmp"
+  str="$iptables -A INPUT -m state"
+  str="$str --state ESTABLISHED,RELATED -j ACCEPT"
+  echo "$str" >> "$tmp"
 fi
 
 # Checking fail2ban support
 if [ -n "$FIREWALL_EXTENSION" ]; then
-	if [ -f "$chains" ]; then
-		while IFS= read -r chain; do
-			parse_object_kv_list "$chain"
-			if [[ "$PORT" =~ ,|-|: ]]; then
-				port="-m multiport --dports $PORT"
-			else
-				port="--dport $PORT"
-			fi
-			echo "$iptables -N fail2ban-$CHAIN" >> "$tmp"
-			echo "$iptables -F fail2ban-$CHAIN" >> "$tmp"
-			echo "$iptables -A fail2ban-$CHAIN -s 0.0.0.0/0 -j RETURN" >> "$tmp"
-			echo "$iptables -A INPUT -p $PROTOCOL $port -j fail2ban-$CHAIN" >> "$tmp"
-		done < "$chains"
-	fi
+  if [ -f "$chains" ]; then
+    while IFS= read -r chain; do
+      parse_object_kv_list "$chain"
+      if [[ "$PORT" =~ ,|-|: ]]; then
+        port="-m multiport --dports $PORT"
+      else
+        port="--dport $PORT"
+      fi
+      echo "$iptables -N fail2ban-$CHAIN" >> "$tmp"
+      echo "$iptables -F fail2ban-$CHAIN" >> "$tmp"
+      echo "$iptables -A fail2ban-$CHAIN -s 0.0.0.0/0 -j RETURN" >> "$tmp"
+      echo "$iptables -A INPUT -p $PROTOCOL $port -j fail2ban-$CHAIN" >> "$tmp"
+    done < "$chains"
+  fi
 
-	if [ -f "$banlist" ]; then
-		while IFS= read -r ban; do
-			parse_object_kv_list "$ban"
-			echo -n "$iptables -I fail2ban-$CHAIN 1 -s $IP" >> "$tmp"
-			echo " -j DROP" >> "$tmp"
-		done < "$banlist"
-	fi
+  if [ -f "$banlist" ]; then
+    while IFS= read -r ban; do
+      parse_object_kv_list "$ban"
+      echo -n "$iptables -I fail2ban-$CHAIN 1 -s $IP" >> "$tmp"
+      echo " -j DROP" >> "$tmp"
+    done < "$banlist"
+  fi
 fi
 
 # Pasring iptables rules
 IFS=$'\n'
 for line in $(sort -r -n -k 2 -t \' $rules); do
-	parse_object_kv_list "$line"
-	if [ "$SUSPENDED" = 'no' ]; then
-		proto="-p $PROTOCOL"
-		port="--dport $PORT"
-		state=""
-		action="-j $ACTION"
+  parse_object_kv_list "$line"
+  if [ "$SUSPENDED" = 'no' ]; then
+    proto="-p $PROTOCOL"
+    port="--dport $PORT"
+    state=""
+    action="-j $ACTION"
 
-		if [[ "$IP" =~ ^ipset: ]]; then
-			ipset_name="${IP#ipset:}"
-			if ! "$BIN/v-list-firewall-ipset" plain | grep "^$ipset_name\s" > /dev/null; then
-				log_event $E_NOTEXIST "IPset IP list ($ipset_name) not found"
-			fi
-			ip="-m set --match-set '${ipset_name}' src"
-		else
-			ip="-s $IP"
-		fi
+    if [[ "$IP" =~ ^ipset: ]]; then
+      ipset_name="${IP#ipset:}"
+      if ! "$BIN/v-list-firewall-ipset" plain | grep "^$ipset_name\s" > /dev/null; then
+        log_event $E_NOTEXIST "IPset IP list ($ipset_name) not found"
+      fi
+      ip="-m set --match-set '${ipset_name}' src"
+    else
+      ip="-s $IP"
+    fi
 
-		# Adding multiport module
-		if [[ "$PORT" =~ ,|-|: ]]; then
-			port="-m multiport --dports ${PORT//-/:}"
-		fi
+    # Adding multiport module
+    if [[ "$PORT" =~ ,|-|: ]]; then
+      port="-m multiport --dports ${PORT//-/:}"
+    fi
 
-		# Accepting all dst ports
-		if [[ "$PORT" = "0" ]] || [ "$PROTOCOL" = 'ICMP' ]; then
-			port=""
-		fi
+    # Accepting all dst ports
+    if [[ "$PORT" = "0" ]] || [ "$PROTOCOL" = 'ICMP' ]; then
+      port=""
+    fi
 
-		# Checking FTP for contrack module
-		if [ "$TYPE" = "FTP" ] || [ "$PORT" = '21' ]; then
-			if [ "$conntrack_ftp" != 'no' ]; then
-				state="-m conntrack --ctstate NEW"
-			else
-				port="-m multiport --dports 20,21,12000:12100"
-			fi
-			ftp="yes"
-		fi
+    # Checking FTP for contrack module
+    if [ "$TYPE" = "FTP" ] || [ "$PORT" = '21' ]; then
+      if [ "$conntrack_ftp" != 'no' ]; then
+        state="-m conntrack --ctstate NEW"
+      else
+        port="-m multiport --dports 20,21,12000:12100"
+      fi
+      ftp="yes"
+    fi
 
-		# Adding firewall rule
-		echo "$iptables -A INPUT $proto $port $ip $state $action" >> "$tmp"
-	fi
+    # Adding firewall rule
+    echo "$iptables -A INPUT $proto $port $ip $state $action" >> "$tmp"
+  fi
 done
 
 # Switching chain policy to DROP
@@ -189,39 +189,39 @@ rm -f "$tmp"
 
 # Checking custom trigger
 if [ -x "$HESTIA/data/firewall/custom.sh" ]; then
-	bash "$HESTIA/data/firewall/custom.sh"
+  bash "$HESTIA/data/firewall/custom.sh"
 fi
 
 # Clean up and saving rules to the master iptables file
 if [ -d "/etc/sysconfig" ]; then
-	/sbin/iptables-save | sed -e 's/[[0-9]\+:[0-9]\+]/[0:0]/g' -e '/^-A fail2ban-[A-Z]\+ -s .\+$/d' > /etc/sysconfig/iptables
+  /sbin/iptables-save | sed -e 's/[[0-9]\+:[0-9]\+]/[0:0]/g' -e '/^-A fail2ban-[A-Z]\+ -s .\+$/d' > /etc/sysconfig/iptables
 else
-	/sbin/iptables-save | sed -e 's/[[0-9]\+:[0-9]\+]/[0:0]/g' -e '/^-A fail2ban-[A-Z]\+ -s .\+$/d' > /etc/iptables.rules
-	iptablesversion="$(iptables --version | head -1 | awk '{print $2}' | cut -f -2 -d .)"
-	sd_unit="/lib/systemd/system/hestia-iptables.service"
-	if [ ! -e "$sd_unit" ]; then
-		echo "[Unit]" >> $sd_unit
-		echo "Description=Loading Hestia firewall rules" >> $sd_unit
-		echo "DefaultDependencies=no" >> $sd_unit
-		echo "Wants=network-pre.target local-fs.target" >> $sd_unit
-		echo "Before=network-pre.target" >> $sd_unit
-		echo "After=local-fs.target" >> $sd_unit
-		echo "" >> $sd_unit
-		echo "[Service]" >> $sd_unit
-		echo "Type=oneshot" >> $sd_unit
-		echo "RemainAfterExit=yes" >> $sd_unit
-		echo "ExecStartPre=-${HESTIA}/bin/v-update-firewall-ipset load" >> $sd_unit
-		if [ "$iptablesversion" = "v1.6" ]; then
-			echo "ExecStart=/sbin/iptables-restore /etc/iptables.rules" >> $sd_unit
-		else
-			echo "ExecStart=/sbin/iptables-restore --wait=10 /etc/iptables.rules" >> $sd_unit
-		fi
-		echo "" >> $sd_unit
-		echo "[Install]" >> $sd_unit
-		echo "WantedBy=multi-user.target" >> $sd_unit
-		systemctl -q daemon-reload
-	fi
-	systemctl -q is-enabled hestia-iptables 2> /dev/null || systemctl -q enable hestia-iptables
+  /sbin/iptables-save | sed -e 's/[[0-9]\+:[0-9]\+]/[0:0]/g' -e '/^-A fail2ban-[A-Z]\+ -s .\+$/d' > /etc/iptables.rules
+  iptablesversion="$(iptables --version | head -1 | awk '{print $2}' | cut -f -2 -d .)"
+  sd_unit="/lib/systemd/system/hestia-iptables.service"
+  if [ ! -e "$sd_unit" ]; then
+    echo "[Unit]" >> $sd_unit
+    echo "Description=Loading Hestia firewall rules" >> $sd_unit
+    echo "DefaultDependencies=no" >> $sd_unit
+    echo "Wants=network-pre.target local-fs.target" >> $sd_unit
+    echo "Before=network-pre.target" >> $sd_unit
+    echo "After=local-fs.target" >> $sd_unit
+    echo "" >> $sd_unit
+    echo "[Service]" >> $sd_unit
+    echo "Type=oneshot" >> $sd_unit
+    echo "RemainAfterExit=yes" >> $sd_unit
+    echo "ExecStartPre=-${HESTIA}/bin/v-update-firewall-ipset load" >> $sd_unit
+    if [ "$iptablesversion" = "v1.6" ]; then
+      echo "ExecStart=/sbin/iptables-restore /etc/iptables.rules" >> $sd_unit
+    else
+      echo "ExecStart=/sbin/iptables-restore --wait=10 /etc/iptables.rules" >> $sd_unit
+    fi
+    echo "" >> $sd_unit
+    echo "[Install]" >> $sd_unit
+    echo "WantedBy=multi-user.target" >> $sd_unit
+    systemctl -q daemon-reload
+  fi
+  systemctl -q is-enabled hestia-iptables 2> /dev/null || systemctl -q enable hestia-iptables
 fi
 
 #----------------------------------------------------------#
