Initial commit: Enable per-domain SSL for mail server

diff --git a/bin/v-update-letsencrypt-ssl b/bin/v-update-letsencrypt-ssl
--- a/bin/v-update-letsencrypt-ssl
+++ b/bin/v-update-letsencrypt-ssl
@@ -29,6 +29,7 @@ lecounter=0
 for user in $($BIN/v-list-users plain |cut -f 1); do
     USER_DATA=$HESTIA/data/users/$user
 
+    # Web
     for domain in $(search_objects 'web' 'LETSENCRYPT' 'yes' 'DOMAIN'); do
         crt_data=$(openssl x509 -text -in $USER_DATA/ssl/$domain.crt)
         not_after=$(echo "$crt_data" |grep "Not After" |cut -f 2,3,4 -d :)
@@ -49,6 +50,42 @@ for user in $($BIN/v-list-users plain |cut -f 1); do
             msg=$($BIN/v-add-letsencrypt-domain $user $domain $aliases)
             if [ $? -ne 0 ]; then
                 echo "$domain $msg"
+            fi
+        fi
+    done
+
+    # Mail
+    for domain in $(search_objects 'mail' 'LETSENCRYPT' 'yes' 'DOMAIN'); do
+        spnd=$(is_object_unsuspended 'web' 'DOMAIN' "$domain")
+        if [ ! -z "$spnd" ]; then
+            echo "$domain is suspended"
+        else
+            crt="$USER_DATA/mail-ssl/$domain.crt"
+            if [ ! -f $crt ]; then
+                echo "$domain Let Encrypt renew failed"
+                update_object_value 'web' 'DOMAIN' "$domain" '$LETSENCRYPT' 'no'
+            else
+                crt_data=$(openssl x509 -text -in $crt)
+                not_after=$(echo "$crt_data" |grep "Not After" |cut -f 2,3,4 -d :)
+                expiration=$(date -d "$not_after" +%s)
+                now=$(date +%s)
+                seconds_valid=$((expiration - now))
+                days_valid=$((seconds_valid / 86400))
+                if [[ "$days_valid" -lt 31 ]]; then
+                    aliases=$(echo "$crt_data" |grep DNS:)
+                    aliases=$(echo "$aliases" |sed -e "s/DNS://g" -e "s/,//")
+                    aliases=$(echo "$aliases" |tr ' ' '\n' |sed "/^$/d")
+                    aliases=$(echo "$aliases" |grep -v "^$domain$")
+                    aliases=$(echo "$aliases" |sed -e ':a;N;$!ba;s/\n/,/g')
+                    msg=$($BIN/v-add-letsencrypt-mail-domain $user $domain $aliases)
+                    if [ $? -ne 0 ]; then
+                        echo "$domain $msg"
+                    fi
+                    if [ $lecounter -gt 0 ]; then
+                        sleep 10
+                    fi
+                    ((lecounter++))
+                fi
             fi
         fi
     done
