Add extra branch check
When update hestia via v-update-sys-hestia-git jaapmarcus random-branch  
When after that calling v-update-sys-hestia-git 
system will check "hestiacp" "random-branch" that might not exists

diff --git a/bin/v-update-sys-hestia-git b/bin/v-update-sys-hestia-git
--- a/bin/v-update-sys-hestia-git
+++ b/bin/v-update-sys-hestia-git
@@ -133,6 +133,11 @@ if [ ! -z "$2" ]; then
 else
     source /usr/local/hestia/conf/hestia.conf
     branch=$RELEASE_BRANCH
+    branch_check=$(curl -s --head -w %{http_code} https://raw.githubusercontent.com/$fork/hestiacp/$branch/src/deb/hestia/control -o /dev/null)
+    if [ $branch_check -ne "200" ]; then
+        echo "ERROR: invalid branch name specified."
+        exit 1
+    fi
 fi
 
 if [ -z "$branch" ]; then
