mail api 100% completed

diff --git a/bin/v_add_mail_account_forward b/bin/v_add_mail_account_forward
--- a/bin/v_add_mail_account_forward
+++ b/bin/v_add_mail_account_forward
@@ -1,8 +1,8 @@
 #!/bin/bash
-# info: add mail account alias aka nickname
-# options: user domain account alias
+# info: add mail account forward address
+# options: user domain account forward
 #
-# The function add new email alias.
+# The function add new email account.
 
 
 #----------------------------------------------------------#
@@ -15,7 +15,7 @@ domain=$(idn -t --quiet -u "$2" )
 domain=$(echo $domain | tr '[:upper:]' '[:lower:]')
 domain_idn=$(idn -t --quiet -a "$domain")
 account=$3
-malias=$4
+forward=$4
 
 # Includes
 source $VESTA/conf/vesta.conf
@@ -27,8 +27,8 @@ source $VESTA/func/domain.sh
 #                    Verifications                         #
 #----------------------------------------------------------#
 
-check_args '4' "$#" 'user domain account alias'
-validate_format 'user' 'domain' 'account' 'malias'
+check_args '4' "$#" 'user domain account forward'
+validate_format 'user' 'domain' 'account' 'forward'
 is_system_enabled "$MAIL_SYSTEM"
 is_object_valid 'user' 'USER' "$user"
 is_object_unsuspended 'user' 'USER' "$user"
@@ -36,30 +36,35 @@ is_object_valid 'mail' 'DOMAIN' "$domain"
 is_object_unsuspended 'mail' 'DOMAIN' "$domain"
 is_object_valid "mail/$domain" 'ACCOUNT' "$account"
 is_object_unsuspended "mail/$domain" 'ACCOUNT' "$account"
-is_mail_new "$malias"
+fwd=$(get_object_value "mail/$domain" 'ACCOUNT' "$account" '$FWD')
+if [ ! -z "$(echo $fwd | grep -w $forward)" ]; then
+    echo "Error: forward $forward exists"
+    log_event "$E_EXISTS $EVENT"
+    exit $E_EXISTS
+fi
 
 
 #----------------------------------------------------------#
 #                       Action                             #
 #----------------------------------------------------------#
 
-# Adding exim alias
-str="$malias@$domain:$account@$domain"
-echo "$str" >> $HOMEDIR/$user/conf/mail/$domain/aliases
+# Adding forward to exim
+if [ -z "$fwd" ]; then
+    fwd="$forward"
+else
+    fwd="$fwd,$forward"
+fi
+
+sed -i "/^$account@$domain:/ d" $HOMEDIR/$user/conf/mail/$domain/aliases
+echo "$account@$domain:$fwd" >> $HOMEDIR/$user/conf/mail/$domain/aliases
 
 
 #----------------------------------------------------------#
 #                       Vesta                              #
 #----------------------------------------------------------#
 
-# Adding vesta alias
-aliases=$(get_object_value "mail/$domain" 'ACCOUNT' "$account" '$ALIAS')
-if [ -z "$aliases" ]; then
-    aliases="$malias"
-else
-    aliases="$aliases,$malias"
-fi
-update_object_value "mail/$domain" 'ACCOUNT' "$account"  '$ALIAS' "$aliases"
+# Updating config
+update_object_value "mail/$domain" 'ACCOUNT' "$account"  '$FWD' "$fwd"
 
 # Logging
 log_history "$EVENT"
diff --git a/bin/v_delete_mail_account_alias b/bin/v_delete_mail_account_alias
--- a/bin/v_delete_mail_account_alias
+++ b/bin/v_delete_mail_account_alias
@@ -1,8 +1,8 @@
 #!/bin/bash
-# info: add mail account alias aka nickname
+# info: delete mail account alias aka nickname
 # options: user domain account alias
 #
-# The function add new email alias.
+# The function deletes email account alias.
 
 
 #----------------------------------------------------------#
@@ -36,29 +36,31 @@ is_object_valid 'mail' 'DOMAIN' "$domain"
 is_object_unsuspended 'mail' 'DOMAIN' "$domain"
 is_object_valid "mail/$domain" 'ACCOUNT' "$account"
 is_object_unsuspended "mail/$domain" 'ACCOUNT' "$account"
-is_mail_new "$malias"
+aliases=$(get_object_value "mail/$domain" 'ACCOUNT' "$account" '$ALIAS')
+if [ -z "$(echo $aliases | grep -w $malias)" ]; then
+    echo "Error: alias $malias is not exist"
+    log_event "$E_NOTEXIST $EVENT"
+    exit $E_NOTEXIST
+fi
 
 
 #----------------------------------------------------------#
 #                       Action                             #
 #----------------------------------------------------------#
 
-# Adding exim alias
-str="$malias@$domain:$account@$domain"
-echo "$str" >> $HOMEDIR/$user/conf/mail/$domain/aliases
+sed -i "/^$malias@$domain:$account/d" $HOMEDIR/$user/conf/mail/$domain/aliases
+aliases=$(echo "$aliases" |\
+    sed -e "s/,/\n/g"|\
+    sed -e "s/^$malias$//g"|\
+    sed -e "/^$/d"|\
+    sed -e ':a;N;$!ba;s/\n/,/g')
 
 
 #----------------------------------------------------------#
 #                       Vesta                              #
 #----------------------------------------------------------#
 
-# Adding vesta alias
-aliases=$(get_object_value "mail/$domain" 'ACCOUNT' "$account" '$ALIAS')
-if [ -z "$aliases" ]; then
-    aliases="$malias"
-else
-    aliases="$aliases,$malias"
-fi
+# Update config
 update_object_value "mail/$domain" 'ACCOUNT' "$account"  '$ALIAS' "$aliases"
 
 # Logging
